### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by CodyPChristian** [lesstif/php-jira-rest-client#1]
Hello,

So far you seem to have the most up to date and working package for JIRA. Would you mind looking into converting it into a Laravel compatible package? I was going to do so but would rather reach out to you first. Thanks

**Comment by lesstif** [comment]
Hi.

Thank you for your suggestion.
I like laravel, it's elegance and powerful framework.
But I am a laravel newbie, and i don't have any time to learning laravel package creation.
I hope that you will contribute here.
Thanks.

**Comment by CodyPChristian** [comment]
Thanks, I would like to but first I have to get your current lib working to do the few things I would like to do. Can I email or Skype chat with you what I need and see if we can get that working? If so I can get this into a Laravel package.

**Comment by Keanor** [comment]
I'm use with zend framework 2. if instead of $path, in JiraClient constructor, set array  then create framework compatibility it easy. (used google translate)

**Comment by Schweppesale** [comment]
@CodyPChristian 

Just drop this into one of your service providers and you should be good.

```
public function register()
    {
        $this->app->bind(ConfigurationInterface::class, function(){
            return new DotEnvConfiguration(base_path());
        });
    }
```

**Comment by DanieleGBX** [comment]
FYI, in general, it's best to have pure php packages and integration packages separately, a Laravel bridge or a Symfony Bundle can definitely exist and provide ease of access, but it's usually best to develop the integration part separately.
