### ISSUE TITLE
improvement: implement Jql query builder

### ISSUE THREAD

**Issue by alexgivi** [lesstif/php-jira-rest-client#103]
It would be great to create class JqlQuery, used to build jql queries for issue searching.
example
```php
$jql = new JqlQuery();
$jql->setProjectKey('PRKEY')
  ->setIssueType('Some Issue Type')
  ->setStatus('Opened');
$result = $issueService->search($jql->getQuery());
```
it would be good possibility to avoid need of searching jql query syntax and possible fields in jira api documentation.
maybe I will create such class in future, when I'll have time to do this.

**Comment by lesstif** [comment]
hi @alexgivi 

thanks for your suggestion.

I hope you will have a time to do it.

thanks.

**Comment by alexgivi** [comment]
Hi @lesstif 
see https://github.com/lesstif/php-jira-rest-client/pull/111

**Comment by lesstif** [comment]
thanks !
