### ISSUE TITLE
Is it possible to get custom field options?

### ISSUE THREAD

**Issue by hobailey** [lesstif/php-jira-rest-client#104]
Ie I can see how you can the info for a custom field, but it doesn't seem to include it's options
I see there is [`getCustomFieldOption()` ](https://github.com/lesstif/php-jira-rest-client/blob/master/src/Field/FieldService.php#L50) but I'm sure it's properly connected up yet?

**Comment by lesstif** [comment]
hi @hobailey 

you can use _getCustomFiledOption_ function with custom field id like below code.

thanks.!

```php
$fieldService = new FieldService();
$ret = $fieldService->getCustomFieldOption(12345);

var_dump($ret);
```

**Comment by hobailey** [comment]
OK great, thanks. Could you include this update in a new release plse?

**Comment by hobailey** [comment]
I've actually just realised that this won't even give what I was after (my misunderstanding as I was looking for the options of a custom field, not the info on a particular option) but [this helped](https://confluence.atlassian.com/jirakb/how-to-retrieve-available-options-for-a-multi-select-customfield-via-jira-rest-api-815566715.html)

**Comment by lesstif** [comment]
I implemented the getEditMeta function.

thanks.

```php
$issueService = new IssueService();

$ret = $issueService->getEditMeta('TEST-123');

var_dump($ret);
```

**Comment by hobailey** [comment]
Oh great, thank you - was using the create meta function that already exists for now :-)
