### ISSUE TITLE
Issue Notify

### ISSUE THREAD

**Issue by R-William** [lesstif/php-jira-rest-client#110]
Hi,

It seems to me very nice to (after creating an issue) share this to some people. With the regular JIRA REST API is this possible via https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-notify maybe this is a nice extension?

**Comment by lesstif** [comment]
hi @R-William.

Issue notification feature is in progress.  i thinks that it will be finish at tomorrow. thanks!

**Comment by lesstif** [comment]
hi. @R-William 

implementation done. [check out doc](https://github.com/lesstif/php-jira-rest-client#issue-notify)

thanks.
