### ISSUE TITLE
search issues, return only certain fields

### ISSUE THREAD

**Issue by wivaku** [lesstif/php-jira-rest-client#112]
When retrieving a specific issue, I can add query parameters to limit which fields to return.
https://github.com/lesstif/php-jira-rest-client#get-issue-info

Question: how can I do the same thing when *searching* for issues?
https://github.com/lesstif/php-jira-rest-client#simple-query

Similar to the [Jira API](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-search-get), where I can submit the JQL and the fields, e.g.:
`{"jql":"project = ABC", "fields":["summary","status","assignee"],}`

**Comment by alexgivi** [comment]
@wivaku    see https://github.com/lesstif/php-jira-rest-client/blob/d10eda8fc29c2fb59af821709c9acdbbf84f799f/src/Issue/IssueService.php#L380
see https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/?_ga=2.215041367.1545323120.1516040140-1168363048.1516040140#api/2/search-search

**Comment by wivaku** [comment]
thanks!
