### ISSUE TITLE
create issue: set custom field string value?

### ISSUE THREAD

**Issue by wivaku** [lesstif/php-jira-rest-client#113]
I want to set the value of a customfield when creating a new ticket.
The field type: string.
The following fails:

```
$newIssueField->setProjectKey("NMI")
	->setSummary("my ticket")
	->setPriorityName("Medium")
	->setIssueType("Bug")
	// ->addCustomField('customfield_10025', ['value' => '12345']) // error: Operation value must be a string
```

Should I set the string value in a different way?
Sorry for this beginner question!

**Comment by lesstif** [comment]
hi.

'custom field 10025' seem like to the string type.

could you change to second parameter to just string value, not array. 

```php
->addCustomField('customfield_10025', '12345')
```

thanks

**Comment by wivaku** [comment]
Did that. Same message.

**Comment by lesstif** [comment]
could you check to what type of custom field 10025? running below code and capture the result please.

````php
$fieldService = new FieldService();

$ret = $fieldService->getAllFields(Field::CUSTOM);

foreach ($ret as $c) {
  if (strstr($c->id, '10025') !== false) {
      var_dump($c->schema);
  }
}
```

**Comment by wivaku** [comment]
I stand corrected, it seems I did not test it correctly.
It was indeed: `->addCustomField('customfield_10025', '12345')`.
Sorry to have bothered you!
Thanks for the response and... the client.
