### ISSUE TITLE
User Worklog

### ISSUE THREAD

**Issue by essteffan** [lesstif/php-jira-rest-client#115]
Hi All.
I need to get user work log for a certain period (like a week).

How can i do that? i can't see any method for that.

Thanks!

**Comment by lesstif** [comment]
hi @essteffan 

This project just implmentation JIRA REST API spec partially, so your request  is need primary support from JIRA standalone.

could you check this feature supported ?(Ex. JQL statement)

**Comment by essteffan** [comment]
I don't know, is my first touch with jira api :)

I see that is supports something like: assignee+%3D+stefan.cuculeac+and+created+<+2018-01-31+and+updated+>+2018-01-01+and+timespent+>+0&maxResults=1000

**Comment by lesstif** [comment]
duplicated #117
