### ISSUE TITLE
remove Label

### ISSUE THREAD

**Issue by R-William** [lesstif/php-jira-rest-client#116]
Hi,

It seems to me very nice to have a choice to remove labels. Or to change them with different text. With the API  is it possible with the code here below.

`"update": {
        "labels": [
            {
                "add": "triaged"
            },
            {
                "remove": "blocker"
            }
        ]
}`

It would be nice if you could make this and maybe this is a nice extension?

**Comment by lesstif** [comment]
hi.

This library has lacks many of the features specified in the Atlassian's REST API documentation,but I can't afford to do it myself.

so please send PR to me after you implement it yourself.

thanks.

**Comment by pniederlag** [comment]
@R-William Would you be able to create a PR or sponsor adding this feature?

**Comment by wapmorgan** [comment]
+1
