### ISSUE TITLE
Worklog between dates 

### ISSUE THREAD

**Issue by essteffan** [lesstif/php-jira-rest-client#117]
Hi Guys.

Is there a way to get logs but between 2 dates? Right now this is the method, but gets all worklogs for a project, but i need it between 2 dates
$worklogs = $issueService->getWorklog($key)->getWorklogs();

Is it possible?

This is my full code:

     try {
                $jql = new JqlQuery();

                $jql->setAssignee($employee)
                    ->addAnyExpression("AND created < 2013-01-31 AND updated > 2018-01-01")
                    ->addAnyExpression("AND timespent > 0");

                $issueService = new IssueService($login);
                $issues = $issueService->search($jql->getQuery(), 0, 100, ["key"]);

                var_dump($issues);
            } catch (JiraException $e) {
                $this->assertTrue(false, 'testSearch Failed : '.$e->getMessage());
            }

            foreach ($issues->issues as $issue) {
                $key = $issue->key;

                // get issue's all worklog
                $worklogs = $issueService->getWorklog($key)->getWorklogs();

                foreach ($worklogs as $worklog){
                    $item = $issueService->getWorklogById($key, $worklog->id);
                    if(Carbon::parse($item->created)->gt(Carbon::now()->startOfMonth())){
                        $data[$employee][Carbon::parse($item->started)->format("m/d/Y") ." - ". $item->issueId] = $item->timeSpent; //or timeSpentSeconds
                    }
                }
            }

**Comment by lesstif** [comment]
JQL Example:
Perform searches based on the work logged at last three days.

[See JQL documentation](https://confluence.atlassian.com/jirasoftwarecloud/advanced-searching-functions-reference-764478342.html#Advancedsearching-functionsreference-startOfDaystartOfDay())

```php
$jql = 'assignee = stefan.cuculeac and  timespent > 0 and worklogDate > startOfDay("-3d") ';
try {
    $issueService = new IssueService();

    $ret = $issueService->search($jql);

    foreach ($ret as $issue) {
        var_dump($issue);
    }
} catch (JiraException $e) {
    $this->assertTrue(false, 'testSearch Failed : '.$e->getMessage());
}

```
