### ISSUE TITLE
Class JiraRestApi\Issue\Watcher does not exist 

### ISSUE THREAD

**Issue by sunlaur** [lesstif/php-jira-rest-client#118]
Version 17.0.0: Could not analyse class: "JiraRestApi\Issue\Watcher" maybe not loaded or no autoloader? Class JiraRestApi\Issue\Watcher does not exist

**Comment by lesstif** [comment]
JiraRestApi\Issue\Watcher class is duplicated with JiraRestApi\Issue\Reporter, so i was remove watcher class, but i didn't update documentation.

just pass watcher's id string as second parameter.

thanks.

```php
$issueService->addWatcher($this->issueKey, 'lesstif' /* watcher's id */);
```
