### ISSUE TITLE
JiraException

### ISSUE THREAD

**Issue by developer-av** [lesstif/php-jira-rest-client#120]
Hi, cow can I parse response json?
`throw new JiraException('CURL HTTP Request Failed: Status Code : '
                 .$this->http_response.', URL:'.$url
                 ."\nError Message : ".$response, $this->http_response);`
![image](https://user-images.githubusercontent.com/15675868/35211204-26fa8918-ff5e-11e7-9b49-8abfd3d41778.png)

**Comment by lesstif** [comment]
your are try to set invalid issue field, would you show me the your code?

**Comment by developer-av** [comment]
I know what this error means, i want parse error message from json

**Comment by lesstif** [comment]
check out "Error Response" section in the JIRA API document. (https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/)

Most error response returning Json based error entity, but this library just throw Exception class.

thanks.
