### ISSUE TITLE
Make a 1.12.2 with Fix to JIraClient

### ISSUE THREAD

**Issue by genio** [lesstif/php-jira-rest-client#123]
Can you please release a 1.12.2 that does nothing other than fix the JiraClient constructor?

The fix was implemented here:
https://github.com/lesstif/php-jira-rest-client/blob/master/src/JiraClient.php#L77-L78

However, the fix isn't available until 1.13.0 and that release bumped the requirement up to PHP v5.5.9 and we're stuck on CentOS 7 with 5.4.16.

I'd like to use the client, but it's either broken or can't be installed.

**Comment by lesstif** [comment]
@genio hi.

i'm not an expert git user,  so i have a problem with releasing older branch.

how would I make a hotfix/patch release to an older branch/release?

**Comment by alexgivi** [comment]
@lesstif I think you can create new branch from old release branch, then add some changes, and make new release with tag 1.12.2 for example from that branch. You can make release even from separate commit. When you make release, you have 2 fields: version tag and target. In target field you can select any branch/commit.

**Comment by lesstif** [comment]
@alexgivi thanks for your kind explanation!

**Comment by lesstif** [comment]
@genio i was release ver 1.12.2.

thanks.

**Comment by genio** [comment]
Awesome.  thank you both!
