### ISSUE TITLE
Filename of attachment

### ISSUE THREAD

**Issue by jpalomoAtr** [lesstif/php-jira-rest-client#124]
Hi!

When I upload a attachment for a issue, the filename is another different in JIRA (php....) respect to original filename. I think that this is possible because in line 270 for JiraClient.php use the function basename and I think that for obtain the same filename is better $upload_file->getClientOriginalName(). 

Can you tell me how to change the basename or upload a fix for this case?

Thanks, regards

**Comment by alexgivi** [comment]
@jpalomoAtr $upload_file is a string, not an object. You can do this:  
```php
$originalFileName = '/some/path/file_name.ext';
$goalName = '/tmp/goal_name.ext';
copy($originalFileName, $goalName);
$issueService->addAttachments($issueId, $goalName);
unlink($goalName);
```

**Comment by lesstif** [comment]
Closed due to inactivity.
