### ISSUE TITLE
Basic auth with password to be deprecated - start using API tokens

### ISSUE THREAD

**Issue by mansilladev** [lesstif/php-jira-rest-client#135]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by monsterlane** [comment]
If you use your email address as your username and your API token as your PW the library still works.

**Comment by embeh** [comment]
At least for Jira 8.15, a token-based request needs an "Authorization: Bearer ...." header and no longer the base64-encoded user:password value.

I had to hack this into the code, as this needs to go directly into the CURLOPT_HTTPHEADER section, which cannot be set in authorization() as it will be overwritten.

A clean solution, with parameters in .env would be really nice.

**Comment by lesstif** [comment]
Personal access token based auth support at this ([commit](56191e480a0bb9ccdf4e2ba9f0a2ed33ac832d67))
