### ISSUE TITLE
Field 'priority' cannot be set. It is not on the appropriate screen, or unknown.

### ISSUE THREAD

**Issue by Programie** [lesstif/php-jira-rest-client#137]
When creating an issue, I get the error "Field 'priority' cannot be set. It is not on the appropriate screen, or unknown." from JIRA.

If I understand the API correctly, the "priority" field should not always be set, especially if it is empty.

**Comment by lesstif** [comment]
hi @Programie 

it was fixed at [1.19.4](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.19.4)

thanks.

**Comment by Programie** [comment]
I just tried to test the fix, but version 1.19.4 does not include it.

See https://github.com/lesstif/php-jira-rest-client/blob/1.19.4/src/Issue/IssueField.php#L131

**Comment by lesstif** [comment]
sorry, it's my mistake.
v 1.19.5 will be  solve your problem.

See https://github.com/lesstif/php-jira-rest-client/blob/1.19.5/src/Issue/IssueField.php#L132

**Comment by Programie** [comment]
Works as expected. Thanks!
