### ISSUE TITLE
IssueField::security

### ISSUE THREAD

**Issue by pniederlag** [lesstif/php-jira-rest-client#143]
I need to set the security field on an issue. There are no getters/setters for security but it does not seem to be within the customFields either.

Do i miss something here or is this a missing feature?

Thx for any help.

https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-set-JIRA-issue-security-level-via-REST/qaq-p/538767

**Comment by lesstif** [comment]
hi @pniederlag 

your request has been applied to the [v-1.19.8](https://github.com/lesstif/php-jira-rest-client/tree/1.19.8).

thanks.

**Comment by lesstif** [comment]
using `setSecurity` setter method.

```php
$issueField = new IssueField();

$issueField->setProjectKey("TEST")
    ->setSummary("something's wrong")
    ->setAssigneeName("lesstif")
    ->setPriorityName("Critical")
    ->setIssueType("Bug")
    // set issue security if you need.
    ->setSecurity(10001 /* security scheme id */)
;
```
