### ISSUE TITLE
don't show changelog

### ISSUE THREAD

**Issue by RmS-biz** [lesstif/php-jira-rest-client#145]
Hello there!

I have issue: 

    $issueService = new IssueService();
	
    $queryParam = [
        'fields' => [  // default: '*all'
			'*all',
//            'summary',
//            'history',
//            'comment',
        ],
        'expand' => [
            'renderedFields',
            'names',
            'schema',
            'transitions',
            'operations',
            'editmeta',
            'changelog',
        ]
    ];
            
    $issue = $issueService->get('DCBNMT-264', $queryParam);
	
	//print "<pre>";
	print    json_encode($issue->fields);	
	//print "</pre>";

"changelog" did not show but in log file it exist. 

How I can fix it?

**Comment by lesstif** [comment]
hi @RmS-biz 

the changelog field not bind to issue field class, yet and i don't know changelog json schema at this time.

could you show me the log file?

**Comment by RmS-biz** [comment]
I sent log to your email
