### ISSUE TITLE
JsonMapper_Exception JSON property "security" in class "JiraRestApi\Issue\IssueField" must not be NULL

### ISSUE THREAD

**Issue by abbasalis** [lesstif/php-jira-rest-client#150]
Hi,

      I am getting this issue nowadays on searching jira issues using IssueService class. It worked fine before. 

      JsonMapper_Exception JSON property "security" in class "JiraRestApi\Issue\IssueField" must not be NULL

Any help would be greatly appreciated.

Thanks,
Abbas

**Comment by lesstif** [comment]
hi @abbasalis 

this bug fixed on [1.20.2](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.20.2).

could you update to recently version?

thanks.

**Comment by abbasalis** [comment]
Thanks... Just now updated and it was resolved...
