### ISSUE TITLE
Unimplemented functions 

### ISSUE THREAD

**Issue by wapmorgan** [lesstif/php-jira-rest-client#159]
Hello. Do you plan to implement functions to work with task attachments?
https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/attachment
I think removing an attachment will be really useful.

**Comment by lesstif** [comment]
thanks for your suggestion.

If you can wait until next week, I will develop during this week a this feature.

**Comment by wapmorgan** [comment]
Oh, that'll be very good.

**Comment by lesstif** [comment]
it's implemented on [v-1.22.0](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.22.0).
check out the [manual](https://github.com/lesstif/php-jira-rest-client#attachment)
