### ISSUE TITLE
Transition Identifier must be an integer

### ISSUE THREAD

**Issue by lucidlemon** [lesstif/php-jira-rest-client#17]
Hey there, I'm trying to implement your gitlab-jira integration but I can't seem so make it work. I get this error on pushing the transition:

```
Error Message : {"errorMessages":["'transition' identifier must be an integer"],"errors":{}}' in /var/www/domain/vendor/lesstif/php-jira-rest-client/src/JiraClient.php:198
```

Is there something wrong?

**Comment by lesstif** [comment]
Hi there.

The example file has transition key named 'Resolved' and 'Closed'.
But some jira installation(especially none english environment) set transition name is other values. 

open the "http:///jira.your.domain/rest/api/2/issue/ISSUE-KEY/transitions?expand=transitions.fields" in your browser and you can found correct Jira transition name then changing integration file to your values.
(ISSUE-KEY will be replace with your jira issue key)
