### ISSUE TITLE
cookie file is placed in current directory and is readable over http

### ISSUE THREAD

**Issue by 4picht** [lesstif/php-jira-rest-client#173]
Hi,

the cookie file location (current working directory) and name (jira-cookies.txt) are hard coded and the variable is protected.

This is unfortunate, because this leaves the file unprotected by default with a predictable name within the directory the web server is serving the files from.

I currently work around this, by creating a directory for each user that is logged in and "chdir" into that directory. It would be much more convenient to be able to override the location and name via the config.

Thanks!

**Comment by lesstif** [comment]
Hi,

I assumed that it's used on private/internal purpose only, so I haven't really considered security.

But as you point out, some user can use it for public service.
so i will fix is vulnerability as soon as possible.

thanks!
