### ISSUE TITLE
editWorklog exception

### ISSUE THREAD

**Issue by bkdotcom** [lesstif/php-jira-rest-client#174]
```PHP
$worklog = $issueService->getWorklogById($issueKey, $worklogId);
$worklog->setTimeSpent("1h 30m");
/*
$worklog now has two conflicting properties:
timeSpent = 1h 30m
timeSpentSeconds = 9000  (the previous value)
*/
$issueService->editWorklog($issueKey, $workLog, $worklogId);
```

throws an exception 
`{"errorMessages":[],"errors":{"timeSpent":"A value is required for manual estimate adjustment"}}'`

googling that error message I found
https://community.atlassian.com/t5/Answers-Developer-Questions/JIRA-REST-API-change-issue-worklog-entry/qaq-p/494934

sure enough, the json string issueService is sending contains
`"timeSpent":"1h 30m" & "timeSpentSeconds":9000`
it needs to be one or the other

`Worklog::setStartedDateTime()` & `Worklog::setTimeSpent)` should update both values...
or..better, the only property should be timeSpentSeconds (single point of reference)...   $timeSpent could be fetched via magic getter (`__get`)

**Comment by lesstif** [comment]
Hi,
Can't you use just one of _setStartedDateTime_ or _setTimeSpent_ function ?

your first suggestion(update both values) is very useful, but this package does't not dependent on the Carbon package, so it 's difficult to manipulate time string.

**Comment by bkdotcom** [comment]
> Can't you use just one of _setStartedDateTime_ or _setTimeSpent_ function ?

That's exactly what I'm doing... only using `setTimeSpent`...


```php
$worklog = $issueService->getWorklogById($issueKey, $worklogId);
$worklog->setTimeSpent("1h 30m");
```

... but I'm doing this on an existing worklog... so it was initialized with timeSpent and timeSpentSeconds properties

**Comment by lesstif** [comment]
ok, i have understand your circumstance.

However, _editWorklog_ is only useful if you want to modify the previous values in the worklogs.

If you're want to logging a new worklog, I think use _addWorklog_ is a to fit for use.

thanks!
