### ISSUE TITLE
Support for "unassigned" Issues on creation

### ISSUE THREAD

**Issue by c-zenker** [lesstif/php-jira-rest-client#177]
Hi,
I was wondering if it is possible to create a JIRA-issue with the assignee of "unassigned". The problem I have is that "unassigned" is not the standard asignee for the Project 'ASDF' (and cannot be changed)

I tried sth. like the following:
```php
$issue = new IssueField();
$issue->setProjectKey('ASDF')
    ->setDescription('bla')
    ->setSummary('blubb')
    ->setAssigneeName(null); // also tried setAssigneeName('')
(new IssueService())->createMultiple([$issue, /* ... */]);
```

But the issues are still created with the standard assignee of the project, not "unassigned".
So is this possible somehow?

**Comment by c-zenker** [comment]
Hi, Thank you for your response.

I checked the JIRA config like you said. The "allow unassigned issue" option seems to be enabled. But I cannot change the default assignee as our "normal" workflow does not allow this. This is a normal user.

Calling the `IssueField::setAssigneeName()` method with null also assignes the issue to the default assignee and not as expected (from https://confluence.atlassian.com/jirakb/how-to-set-assignee-to-unassigned-via-rest-api-in-jira-744721880.html) to "unassigned"

Setting the Assignee to "unassigned" is indeed working if I create the ticket first and then go for `changeAssignee('ASDF', null)` of the IssueService. But this has a huge drawback: The ticket is at first created with the default assignee and *then changed to unassigned. So e.g. mails are triggered for the user.

Digging into the code showed me that the problem could relate to the fix of https://github.com/lesstif/php-jira-rest-client/issues/126 in `IssueField::jsonSerialize()` where an empty assignee (like null) is removed from the serialized issue?

**Comment by lesstif** [comment]
Hi, thanks for your kindly comment.

Based on the information you gave me I  added new functions to met your requirements while maintaining compatibility.

if you want to set assignee to unassigned, just call _setAssigneeToUnassigned_ method.

```php
$issueField = new IssueField();

$issueField->setProjectKey('TEST')
            ->setIssueType('Bug')
            ->setAssigneeToUnassigned()
 ;
```

it was applied at [v1.28.0](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.28.0)

thanks!
