### ISSUE TITLE
issues do not support unassigned

### ISSUE THREAD

**Issue by jasonpjohnson** [lesstif/php-jira-rest-client#18]
When attempting to create a new issue with no assignee, I attempted to just remove ->setAssigneeName, passing a name value of null, passing a name value of "".

sample code to reproduce 

        $issueField = new IssueField();
        $issueField->setProjectKey("TEST")
            ->setSummary($summary)
            ->setAssigneeName("")
            ->setPriorityName($priority)
            ->setIssueType($type)
            ->setDescription($description);

        $issueService = new IssueService();

        $ret = $issueService->create($issueField);
        return $ret;

It seem most natural that SetAssigneeName would be come optional

https://confluence.atlassian.com/display/JIRAKB/How+to+Set+Assignee+to+Unassigned+via+REST+API+in+JIRA

Errors:
 Fatal error: Uncaught exception 'JiraRestApi\JiraException' with message ' in /var/www/html/composer/vendor/lesstif/php-jira-rest-client/src/JiraClient.php on line 196
( ! ) JiraRestApi\JiraException: CURL HTTP Request Failed: Status Code : 400, URL:http://jira.sweetwater.com/rest/api/2/issue Error Message : {"errorMessages":[],"errors":{"assignee":"data was not an object"}} in /var/www/html/composer/vendor/lesstif/php-jira-rest-client/src/JiraClient.php on line 196
Call Stack
#	Time	Memory	Function	Location
1	0.0006	254200	{main}( )	../test.php:0
2	0.0999	1332808	my_jira->new_fourd_project( )	../test.php:15
3	0.1076	1376352	JiraRestApi\Issue\IssueService->create( )	../my_jira.php:43
4	0.1086	1388808	JiraRestApi\JiraClient->exec( )	../IssueService.php:45

**Comment by lesstif** [comment]
hi there.
i'm implemented your ticket on current master branch.

check it out and share your result on this ticket.

If no problem i will release new minor version.

**Comment by jasonpjohnson** [comment]
Thanks I will test it today.
