### ISSUE TITLE
More than 1 Environment

### ISSUE THREAD

**Issue by calawers** [lesstif/php-jira-rest-client#192]
Dear Team,

Good Job with this library.

I'm just wondering if there is any chance to add more than 1 environment and do the request in all of them at the same time.

Regards,

**Comment by lesstif** [comment]
hi @calawers .

this library does not support multiple environment.
if you need it, you could use [ArrayConfiguration](https://github.com/lesstif/php-jira-rest-client#use-array) class.

thanks.
