### ISSUE TITLE
Multiple requests per second without timeout

### ISSUE THREAD

**Issue by amankograver** [lesstif/php-jira-rest-client#194]
Hi, we are got problems with multiple requests per second without timeout using this extension. It crashes our server. Problems here
https://github.com/lesstif/php-jira-rest-client/blob/master/src/JiraClient.php#L357
we are getting this error:
exception 'yii\base\ErrorException' with message 'Maximum execution
time of 60 seconds exceeded' in
/var/www/.../vendor/lesstif/php-jira-rest-client/src/JiraClient.php:357
then system administrator of jira calling us and say that we have a problems with too big number of requests per second.

Please help us!

**Comment by lesstif** [comment]
Hi.

do you running many batch issue registration or large file attachment?

if you can't modifying max execution parameter, i think that you need to slice batch job count.

thanks.

**Comment by amankograver** [comment]
I checked request with error. It has 322 attachments o.O
try to reproduce and i cant do this. i'm sure that i call self::$issueService->addAttachments method with $filePathArray param 3 elements array

**Comment by lesstif** [comment]
did you mean that trying to attach 322 files in the single session?

If so, it will be take a long long time to add 322 files and max execution time exceed exception occur.
