### ISSUE TITLE
Create project method

### ISSUE THREAD

**Issue by myki57** [lesstif/php-jira-rest-client#195]
Hi,
your plugin is so much usefull for me, but I would like to know if you have planned to develop a "create project method". 

It seems possible in API : 
https://developer.atlassian.com/cloud/jira/platform/rest/v3/?utm_source=%2Fcloud%2Fjira%2Fplatform%2Frest%2F&utm_medium=302#api-api-3-project-post

Thanks in advance for your answer.

**Comment by myki57** [comment]
If it's not something that you've planned, can you share any workaround or ways to you your dev to create project ?

Thanks again.

**Comment by lesstif** [comment]
hi,

check out this manual. (https://github.com/lesstif/php-jira-rest-client#create-project)

thanks!
