### ISSUE TITLE
Issuetype scheme from createproject method

### ISSUE THREAD

**Issue by myki57** [lesstif/php-jira-rest-client#208]
Hi everyone,
Thanks for your project it's amazing how it can help us. 

I would like to know if it's possible for you guys to add IssueType scheme when using a create project method ?

Thanks very much for your answer.

Cheers.

**Comment by myki57** [comment]
Sorry I didn't see the JIRA cloud api, the Issuetype scheme is not available on the API. 

Maybe you can help me, I would like to create issues in a project with specials type of tasks. With the API it's seems that is not possible to create a project from a specific template (home made). You only use projectTemplateKey from Atlassian. 

So here's my question, how I can create a project from an existing project rather that a JIRA template ?Or how can assign a specifc type of task to a created project ?

Thanks in advance.

**Comment by lesstif** [comment]
hi, @myki57 .

i think that JIRA does not support cloning project from exist project basically , so this library can not support do it.

if you need it, you should use third party plugin, for example 
[clone project for Jira plugin](https://marketplace.atlassian.com/apps/1211373/clone-project-for-jira?hosting=server&tab=overview).

thanks.

**Comment by myki57** [comment]
Hi @lesstif
Thanks for your answer. We have a jira cloud version. So I understand that in cloud based version no cloning option is available yet. 

Am I right?

**Comment by lesstif** [comment]
Hi @myki57.

I have not used cloud version , so i don't know your are right.

anyway JIRA server version also does not support cloning project, but it has third party plugin for do it.

thanks.
