### ISSUE TITLE
Get Attachment Info not found

### ISSUE THREAD

**Issue by joshxsm** [lesstif/php-jira-rest-client#210]
Quiero acceder a los enlaces a través del usuario de la API de Jira (Admin) pero la clase get Attachment no funciona correctamente por algún motivo:

``<link href="css/lightbox.css" rel="stylesheet">
                  <script src="js/lightbox.js"></script>
                  <?php

                  //ADJUNTOS DEL TICKET
                // 
                require 'vendor/autoload.php';

                use JiraRestApi\Attachment\AttachmentService;
                use JiraRestApi\JiraException;

                try {
                    $attachmentId = 161485;

                    $atts = new AttachmentService();
                    $att = $atts->get($attachmentId);

                    var_dump($att);
                } catch (JiraException $e) {
                    print("Error Occured! " . $e->getMessage());
                }

                  ?>

                </div>
``

**Comment by lesstif** [comment]
hi @joshxsm.

could your show me the exception log message or other information please?
