### ISSUE TITLE
Array to string  conversion

### ISSUE THREAD

**Issue by kowalk** [lesstif/php-jira-rest-client#221]
https://github.com/lesstif/php-jira-rest-client/blob/58be2843e81fd1e5988996e7fcd7b2ca136da8d7/src/JiraClient.php#L174

To reproduce please call method removeUserFromGroup from src/Group/GroupService.php

**Comment by lesstif** [comment]
hi @kowalk 

it's resolved in the [v1.34.0](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.34.0).

thanks.
