### ISSUE TITLE
Slow load when loading tickets in Jira 6

### ISSUE THREAD

**Issue by joshxsm** [lesstif/php-jira-rest-client#226]
Good, simply comment if this application in functional with the version 7 of Jira and at the same time if it improved the performance of the consultations towards the API since when I try to load + of 150 issues the server takes more than 10 sec in load. In 2 weeks I will install in my area the new Jira 7

Greetings and thanks, good work

**Comment by lesstif** [comment]
@joshxsm  do you using JQL for bulk fetch with pagination?
