### ISSUE TITLE
Anyone know how to make this work w/ Laravel 5.1?

### ISSUE THREAD

**Issue by ssenaria** [lesstif/php-jira-rest-client#23]

**Comment by lesstif** [comment]
this is not seamlessly integrated with laravel(no service provider, no facade) yet, but you can use it like common PHP composer package.

**Comment by codybutz** [comment]
@lesstif The only issue is that Laravel 5.0+ requires phpdotenv 2.0+ and the requirement on this project is 1.0, therefore there are issues installing it through composer.

**Comment by lesstif** [comment]
@codybutz Laravel 5.0, 5.1 requires phpdotenv 1.0, but 5.2 requires 2.0, so I believe this is only affect 5.2+.
are you running the 5.2 version?

**Comment by codybutz** [comment]
@lesstif Yes, I apologize. Laravel 5.2 requires phpdotenv 2.0. If you could make this repository allow >1.0 that would be great so it is compatible with Laravel 5.2!

**Comment by lesstif** [comment]
@codybutz  i was released new version 1.6.0. would you test this version with your laravel project?

thanks

**Comment by tschifftner** [comment]
The new requirement breaks non-laraval installs - 1.5.2 is working.

**Comment by lesstif** [comment]
@tschifftner 1.6 just changed phpdotenv 1.0 to 2.0. Are you already used or dependent to phpdotenv 1.0 in your project?

**Comment by tschifftner** [comment]
No, I started with an empty composer file like:

```
{
    "require": {
        "lesstif/php-jira-rest-client": "dev-master"
    }
}
```

**Comment by lesstif** [comment]
@tschifftner i was fixed this bug . thanks very much.
