### ISSUE TITLE
Unauthorized error when cookie has expired

### ISSUE THREAD

**Issue by yarnaudov** [lesstif/php-jira-rest-client#232]
When **COOKIE_AUTH_ENABLED=true** cookie file is successfully created after first request is send (using user/pass).
But later if cookie is expire, but file exists [JiraClient ](https://github.com/lesstif/php-jira-rest-client/blob/master/src/JiraClient.php#L466)does not try to login with user/pass, instead it just fails with 401.

Is there a way to implement logic that will try login with user/password if cookie login fails?

**Comment by lesstif** [comment]
hi @yarnaudov .

sorry for the late reply.

According to [atlassian's develop guide](https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-cookie-based-authentication/), cookie based authentication deprecated.

i think that you should use the basic authentication on jira. (at this time OAUTH authentication not  implemented yet)

thanks.
