### ISSUE TITLE
vlucas/phpdotenv v3 support

### ISSUE THREAD

**Issue by andrey-helldar** [lesstif/php-jira-rest-client#234]
The new version of the Laravel framework works with the 3rd version of the package `vlucas/phpdotenv`.
Because of this problem, I can not update the application to the latest version.

**Comment by lesstif** [comment]
hi @andrey-helldar 

sorry for late reply.

this issue fixed at [1.36.0](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.36.0).

thanks

**Comment by andrey-helldar** [comment]
@lesstif, nice! Thanks! 🍻
