### ISSUE TITLE
Implement GDPR related changes to the Jira Cloud API

### ISSUE THREAD

**Issue by MartinRamm** [lesstif/php-jira-rest-client#235]
[Atlassian announced](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) that it will replace references to the `username` of a user with the `accountId` of the user, to improve security. After the 29th of March 2019, usages of `username` will also no longer be returned by the server nor accepted on incoming requests.

(Let me ask naïvely, completely ignoring that this causes a lot of work in a short period of time): Are you planning on supporting this change?

**Comment by lesstif** [comment]
hi @MartinRamm 

sorry for late reply.

for the honest, i'm not using atlassian cloud products, and i'm not a European, so i'm not fully understanding GDPR issue.

could you explain to me what is the your problem?

thanks.

**Comment by adamlevenson** [comment]
@MartinRamm @lesstif basically they got rid of "usernames" for GDPR security purposes. For the purposes of using this package, just use your account email as the "username" and it works perfectly.
