### ISSUE TITLE
Unable to create Jira issue with accountId from Rest

### ISSUE THREAD

**Issue by swathiramesh20** [lesstif/php-jira-rest-client#237]
As per new Jira GDPR compliance the field name, key has to be deprecated. So I'm trying to create an issue by specifying assignee with accountId but I'm unable to find function to pass account Id. I have tried the below.

$issueField = new IssueField();
				$issueField->setProjectId(PROJECTID)
				->setSummary(SUMMARY)
				->setIssueType("Bug")
				->setAssigneeName(ACCOUNTID)
				->setPriorityName(PRIORITY);
				$issueDetails = $issueService->create($issueField);

**Comment by lesstif** [comment]
hi @swathiramesh20 

i'm so sorry, i'm not have jira cloud account.

could you know that how can i get the free jira cloud account for testing purpose?

**Comment by swathiramesh20** [comment]
Hi @lesstif 
you can try the cloud for a free trial. Check the below link
[https://www.atlassian.com/software/jira/try]

**Comment by lesstif** [comment]
hi @swathiramesh20 

I just pushed a devel versionon the development branch that supports createIssue using acccountID with REST API V3.

[check out sample code here](https://github.com/lesstif/php-jira-rest-client/tree/develop#create-issue-using-rest-api-v3).

you need to set *JIRA_REST_API_V3=true* into the .env file.

**Comment by swathiramesh20** [comment]
Thank you @lesstif Will work on this and get back to you if I need further help.

**Comment by swathiramesh20** [comment]
Hi @lesstif 
I have tried to update package from 1.7 to 1.19 by composer update. But I cannot see any changes in Issue/IssueField.php the function setAssigneeAccountId() was not added to IssueField.php

**Comment by lesstif** [comment]
hi @swathiramesh20.

you should use **develop** branch as follows, not master branch.

```json
"require": {
        "lesstif/php-jira-rest-client": "dev-develop"
}
```

**Comment by swathiramesh20** [comment]
Hi @lesstif 
It worked fine. Please let us know the version number once you update it to master branch.
