### ISSUE TITLE
Worklogs missing from tempo

### ISSUE THREAD

**Issue by jameswilson** [lesstif/php-jira-rest-client#240]
Not sure if this is necessarily an error with this package or with something internal, but wanted to see if someone else was having issues using the JIRA rest api to submit worklogs against jira issues, and the worklogs not showing up in Tempo.

In my case generating the Worklog using the IssueService works fine, and an ID is generated, but I cannot see the worklog entries in the issue on Jira cloud web interface or in tempo reports.

I've been using this fine for years, and it literally stopped working within the past week.

Code snippet:
```php
 try {
  $workLog = new Worklog();
  $workLog->setComment($comment)
    ->setStarted($date)
    ->setTimeSpent($hours . 'h');
  $issueService = new IssueService();
  $ret = $issueService->addWorklog($issueKey, $workLog);
  $workLogid = $ret->{'id'};
  print "✅  logged ($workLogid) | ${issueKey} | ${datetime} | ${hours}h | ${comment} |\n";
} catch (JiraException $e) {
  print "🛑  ️" . $e->getMessage();
}
```

I'm not entirely sure how to continue troubleshooting?  Should I be able to do something with those worklog IDs via the UI to confirm they're there?

**Comment by lesstif** [comment]
hi @jameswilson .

first of all, i'm not use JIRA cloud and tempo plugin, so i think that i can't fully understanding your circumstances and problem.

i knew atlassian jira cloud deprecated REST v2 and released v3 api for  GDPR-related changes.

so if your problem caused by v3 api, i think that you can't use other feature like user create, watcher, view etc.

are the other functions working fine?

**Comment by jameswilson** [comment]
Thanks for the reply @lesstif . I contacted support and it turned out that there was just a processing delay.  I waited one more day and checked Jira and Tempo again, and the worklogs were present.   I've been using this for 2 years and never noticed a delay like this before.   I'm closing this.
