### ISSUE TITLE
Unable to add attachments to jira issue

### ISSUE THREAD

**Issue by swathiramesh20** [lesstif/php-jira-rest-client#249]
I have used addAttachments() function to upload attachments to an existing Jira issue.
$issueService->addAttachments($jirakey, $filePath);
The call returns a CURL Error that file doesn't exist but the file resides at the specified path. Help me out on adding an attachment to the issue

**Comment by lesstif** [comment]
@swathiramesh20 what is the path types using by you? relative path or absolute path?
could you check the app's current working directory using _getcwd_ function?

**Comment by swathiramesh20** [comment]
I have used methods like 
echo base_path();
echo public_path();
echo storage_path();
but the function is not working. My file resides at
'/var/www/html/myproject/storage/app/public/myattachments/8r.jpeg'
I have specified the path as
$filePath = public_path().'/storage/myattachments/'.$storedFileName;
but the function is not working

**Comment by lesstif** [comment]
laravel's _public_path()_ helper returning PROJECT_ROOT/public, so your code not correctly generate file's full path name.

could you change either A or B  and try again please?

**A**
```
$filePath = base_path().'/storage/myattachments/'.$storedFileName;
```

**B**
```
$filePath = storage_path().'/myattachments/'.$storedFileName;
```

for your  convenience debugging, i suggest typing bottom code on the tinker console.

```
file_exist( storage_path().'/myattachments/'.$storedFileName);
```

**Comment by lesstif** [comment]
@swathiramesh20  sorry, i miss understood.

are you ran _php artisan storage:link_ command?

your public/storage folder point to 'storage/app/public' ?

**Comment by swathiramesh20** [comment]
Thank you @lesstif the function base_path() has worked.
