### ISSUE TITLE
Exception [ 0 ]: Failed calling JiraRestApi\Issue\Reporter::jsonSerialize()

### ISSUE THREAD

**Issue by vickoman** [lesstif/php-jira-rest-client#25]
I've made some changes into kohanna app when i try in local enviroment works good but when deploy the changes i have this issue. APPPATH/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php [ Line 43 ].

Any idea why?

**Comment by lesstif** [comment]
@vickoman  would you show me the more informations(stack trace, json data, logging, etc.)?
