### ISSUE TITLE
Multiple Attachments not working anymore

### ISSUE THREAD

**Issue by jlu-pp** [lesstif/php-jira-rest-client#251]
Uploading multiple attachments in one request does not work with Version 1.37.0. This is probably caused by the changes of #241 .

Only the last attachment of each request ends up correctly in JIRA. It does not matter if a ticket is created or updated.

Downgrading to 1.36.0 fixes the problem.

**Comment by lesstif** [comment]
@jlu-pp it'was fixed [1.38.0](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.38.0).
thanks.
