### ISSUE TITLE
Jql ignored during IssueService search

### ISSUE THREAD

**Issue by durino13** [lesstif/php-jira-rest-client#256]
No matter what Jql parameters I add, I always get all JIRA issues. Any idea, what is wrong here?

```<?php

require 'vendor/autoload.php';

use JiraRestApi\Issue\IssueService;
use JiraRestApi\Issue\JqlQuery;
use JiraRestApi\JiraException;

$jql = new JqlQuery();

$jql->setProject('project_name')
    ->setAssignee('assignee_name');

try {
    $issueService = new IssueService();
    $issues = $issueService->search($jql->getQuery())->getIssues();

    foreach ($issues as $issue) {
        echo $issue->key;
    }

} catch (JiraException $e) {
    var_dump($e->getMessage());
    exit;
}```

**Comment by lesstif** [comment]
hi @durino13  i'm sorry for late reply.

what is the JqlQuery class? could you to show generated JQL query string to me?
thanks.

**Comment by oldy777** [comment]
@lesstif The problem here:
\JiraRestApi\JiraClient::exec
`curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);`

Data must be in request body.

**Comment by ikdekker** [comment]
> @lesstif The problem here:
> \JiraRestApi\JiraClient::exec
> `curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);`
> 
> Data must be in request body.

Isn't this already in the library? This is not fixed for me.

**Comment by DivineOmega** [comment]
I'm seeing the same issue with JQL being ignored during an issue search.

**Comment by mogilyovkin-taptima** [comment]
Same problem

**Comment by staabm** [comment]
hmm... I am wondering why it works for me.

**Comment by mogilyovkin-taptima** [comment]
@staabm 
```
$jql = 'status != Closed';
try {
    $this->jiraApiIssueClient = new IssueService(...);
    $response = $this->jiraApiIssueClient->search($jql, $startAt, $maxResults);
} catch (JiraException | JsonMapper_Exception $e) {
    $msg = 'Error occurred while getting users from Jira : %s';
    $this->logError(sprintf($msg, $e->getMessage()));
}
```
returns all issues, ignoring status.
php 7.1
curl 7.69.1

**Comment by staabm** [comment]
I am using

```php
$jql = 'project = "KUNZ46" and fixVersion = "Fast Track" and status != Closed';

$issueService = new IssueService($this->jiraConfig);

$maxResults = 250;
$startAt = 0;

$result = $issueService->search($jql, $startAt, $maxResults, [], ['projects.issuetypes.fields', 'changelog']);
```

and it works perfectly fine.

does your JQL work if you put it 1:1 into the jira-issue filter?

which jira version? we are on v8.2.3

**Comment by mogilyovkin-taptima** [comment]
@staabm Jira Cloud. Yes, when I put jql into jira-issue filter it works fine.

**Comment by mogilyovkin-taptima** [comment]
It seems like problems on jira side. Because same problem occurs, when I send request via Postman

**Comment by staabm** [comment]
> It seems like problems on jira side. Because same problem occurs, when I send request via Postman

Could you open a support case on your cloud hoster?

**Comment by mogilyovkin-taptima** [comment]
> > It seems like problems on jira side. Because same problem occurs, when I send request via Postman
> 
> Could you open a support case on your cloud hoster?

Already did it. Waiting for response

**Comment by mogilyovkin-taptima** [comment]
@staabm I got answer from support. The problem is in URL. If you put it without https prefix like "taptima.atlassian.net/rest/api/2/search" then jira ignores jql. But if you put "https://taptima.atlassian.net/rest/api/2/search" everything works.

**Comment by scottconnerly** [comment]
Legit. This solved my problem too.
We need to enforce https at either \JiraRestApi\Configuration\AbstractConfiguration::getJiraHost() or
\JiraRestApi\Configuration\DotEnvConfiguration::__construct

**Comment by dlicheva** [comment]
You can set your Jira host to `https` in your `.env` file:

`JIRA_HOST=https://[your app].atlassian.net`

That resolved the issue for me.
