### ISSUE TITLE
ticket search due to dependency change

### ISSUE THREAD

**Issue by stephane34123** [lesstif/php-jira-rest-client#258]
Hi,

The library seems broken due to a change of this dependency code : netresearch/jsonmapper

When performing a ticket search there is this error

Uncaught ReflectionException: Class \\JiraRestApi\\Issue\\mixed does not exist in 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php:585\nStack trace:\n#0 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php(585): ReflectionClass->__construct('\\\\JiraRestApi\\\\Is...')\n#1 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php(277): JsonMapper->createInstance('\\\\JiraRestApi\\\\Is...', false, Object(stdClass))\n#2 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php(278): JsonMapper->map(Object(stdClass), Object(JiraRestApi\\Issue\\IssueField))\n#3 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php(399): JsonMapper->map(Object(stdClass), Object(JiraRestApi\\Issue\\Issue))\n#4 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php(265): JsonMapper->mapArray(Array, Array, '\\\\JiraRestApi\\\\Is...', 'issues')\n#5 
.../vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php(532): JsonMapper->map(Object(stdClass), Object 
.../vendor/netresearch/jsonmapper/src/JsonMapper.php 585

Thanks

**Comment by leonardfischer** [comment]
Yep, same here. I found out that the problem is related to the `issuetype`, meaning this here causes the error:

```
$issues = $issueService
    ->search($jql, 0, 500, ['id', 'key', 'issuetype'])
    ->getIssues();
```

While the same request (without `issuetype`) will work perfectly fine... But now, of course, the issue type is missing in the result and it's very important to me :(

Happenes since yesterday with Jira Cloud (both using V2 and V3 Rest API)
