### ISSUE TITLE
Set resolution of issue?

### ISSUE THREAD

**Issue by nessthehero** [lesstif/php-jira-rest-client#266]
Good morning,

There does not seem to be an obvious way to set the resolution of an issue. There's no specific setter function for this, though $resolution is a public property of IssueField.

What would be the best way to set this?

My code is set up to transition an issue to Closed but it doesn't update the resolution at the same time, so that's why I'm looking to do that.

Thanks,

**Comment by gzmarchenko** [comment]
I'd say you need to update resolution through your workflow for your 'close' action.

**Comment by nessthehero** [comment]
I figured as much. Resolution is such a weird field. Thanks.

**Comment by enduro44** [comment]
If anyone is still interested I managed to set resolution using transition fields, to construct post like in https://community.atlassian.com/t5/Jira-questions/How-to-add-resolution-details-in-JIRA-Rest-API/qaq-p/1570641 Nivaldo Georg Junior suggestion.
Something like this:
```
$fields = new IssueField(true);
$resolution = new stdClass();
$resolution->name = 'Done';
$fields->resolution = $resolution;

$transition = new Transition();
$transition->setTransitionName('Done');
$transition->fields = $fields;
$issueService = new IssueService();
$issueService->transition($issue->id, $transition);
```
