### ISSUE TITLE
The PHP 5.5 should not be failed during Travis CI build

### ISSUE THREAD

**Issue by peter279k** [lesstif/php-jira-rest-client#267]
According to the [Travis CI build log](https://travis-ci.org/lesstif/php-jira-rest-client/jobs/567529068), the PHP 5.5 is failed because the Travis use default dist has been changed.

According to the official [Travis CI build log](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment), the default dist is `Xenial`. The original dist is `Trusty`.

And the `php-5.5` is only included in Travis `Trusty` dist.

Another problem is about PHPUnit version definition.

According to the [official PHPUnit website](https://phpunit.de/getting-started/phpunit-5.html), the `PHPUnit 5` requires `php-5.6` version at least.

And the `PHPUnit 4.x` requires `php-5.3`, `php-5.4` and `php-5.5`.

To resolve PHPUnit version definition issue, I think we have two following suggestions:

- Drop `php-5.5` version support.
- Add `PHPUnit 4.8` version inside `require` block in `composer.json`.

**Comment by lesstif** [comment]
thanks to your comment.

I was dropped PHP 5.5 and upgraded the minimum required PHP version to 5.6.
