### ISSUE TITLE
Update Issue Status

### ISSUE THREAD

**Issue by Namepalli** [lesstif/php-jira-rest-client#270]
Was just wondering to see if i can update the issue status through an api. And is there a possibility to get list of all issues in the project.

**Comment by lesstif** [comment]
hi @Namepalli 

i sorry for lately reply.

* if you want to update the issue status, you could using issue transition function. 
see  link https://github.com/lesstif/php-jira-rest-client#perform-a-transition-on-an-issue.
* if you want to get all issues in the project, you could using the JQL statement.
see  link if you want to get all issues in the project, you could using the JQL statement.
