### ISSUE TITLE
Parse error: syntax error, unexpected

### ISSUE THREAD

**Issue by matiasmenker** [lesstif/php-jira-rest-client#28]
Parse error: syntax error, unexpected '[' in /home/web/interiorvista/tickets/dev/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php on line 210

**Comment by lesstif** [comment]
What version of PHP and php-jira-rest-client package are you using?

**Comment by matiasmenker** [comment]
I fix this problem, the problem was the version true, but now i have all perfect, and i have this problem;

Fatal error: Class 'JiraRestApi\JIRAException' not found in /opt/lampp/htdocs/vendor/lesstif/php-jira-rest-client/src/JiraClient.php on line 348

When i try to add attachment;

    $issueService = new IssueService();
                $issueKey = 'PT-13';

                // multiple file upload support.
                $ret = $issueService->addAttachments($issueKey,array('/home/centos/Downloads/mentor-half.png'));

                
            echo '<pre>';
            print_r($issueService);
            print_r($ret);
            echo '</pre>';
            die();


Can you help me?

**Comment by lesstif** [comment]
are your inserted *require 'vendor/autoload.php';* statement at top of the code. ?

**Comment by matiasmenker** [comment]
Yes i have in the main conf.php

// Configure the Twig template system
require_once $CONF->vendor . 'autoload.php';
Twig_Autoloader::register(true);
$TWIG = new Twig_Environment(new Twig_Loader_Filesystem($CONF->template));

And i hace .env configurate good aswell.


I dont know what happend :(


2016-04-11 16:53 GMT+02:00 KwangSeob Jeong <notifications@github.com>:

**Comment by lesstif** [comment]
composer download depencenties into the vendor directory.
you can just start using classes from it, and they will be autoloaded.

```php
<?php
require __DIR__ . '/vendor/autoload.php';
```

check the $CONF variable's value at runtime and fix it.

**Comment by matiasmenker** [comment]
$CONF->app          = $_SERVER['DOCUMENT_ROOT'];
$CONF->baseUrl      = '/app/';

$CONF->private      = preg_replace('#/+#', '/', $CONF->app.'/private/');
$CONF->vendor       = preg_replace('#/+#', '/', $CONF->app.'/vendor/');
$CONF->template     = preg_replace('#/+#', '/',
$CONF->app.$CONF->baseUrl.'/templates');

$CONF->lang         = 'en_GB';
$CONF->strings      = array();


// Configure the Twig template system
require_once $CONF->vendor . 'autoload.php';
Twig_Autoloader::register(true);
$TWIG = new Twig_Environment(new Twig_Loader_Filesystem($CONF->template));



I have good config, and work good for all, i dont understan the problem

2016-04-12 8:38 GMT+02:00 KwangSeob Jeong <notifications@github.com>:

**Comment by matiasmenker** [comment]
In mi autoload.php i have this:

<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit0411751073be3a2e7da40e156a5789a8::getLoader();

2016-04-12 9:31 GMT+02:00 Matias Menker <menkermatias@gmail.com>:

**Comment by matiasmenker** [comment]
Im tring to get all the projects with your library and i get this msg:

Fatal error: Uncaught exception 'JiraRestApi\JiraException' with message
'CURL HTTP Request Failed: Status Code : 401, URL:
https://interiorvista.atlassian.net/rest/api/2/project Error Message :
<html> <head> <title>Unauthorized (401)</title> 
<script type="text/javascript">var contextPath = '';</script> <script>
window.WRM=window.WRM||{};window.WRM._unparsedData=window.WRM._unparsedData||{};window.WRM._unparsedErrors=window.WRM._unparsedErrors||{};
WRM._unparsedData["com.atlassian.plugins.atlassian-plugins-webresource-plugin:context-path.context-path"]="\"\"";
WRM._unparsedData["jira.webresources:feature-flags.feature-flag-data"]="{\"enabled-feature-keys\":[\"jira.plugin.devstatus.smartcommits.dvcs.enabled\",\"nps.survey.inline.dialog\",\"rotp.admin.shortcuts\",\"com.atlassian.jira.projects.issuenavigator.cachefix\",\"jira.plugin.devstatus.phasetwo\",\"jira.frother.reporter.field\",\"atlassian.rest.xsrf.legacy.enabled\",\"jira.administration.workflow.validation\",\"
ondemand.la in
/opt/lampp/htdocs/vendor/lesstif/php-jira-rest-client/src/JiraClient.php on
line 201

the .env its in the root, so i donrt know what  happends...

2016-04-12 9:31 GMT+02:00 Matias Menker <menkermatias@gmail.com>:

**Comment by lesstif** [comment]
I'm found case typo error with JiraException class naming.

i will fixes it and release new version as soon as possible.

**Comment by matiasmenker** [comment]
Ok perfect!

2016-04-12 11:11 GMT+02:00 KwangSeob Jeong <notifications@github.com>:

**Comment by lesstif** [comment]
you need create .env file and setting jira credential info into it.
