### ISSUE TITLE
Started getting error: Operation value must be an Atlassian Document

### ISSUE THREAD

**Issue by robguida** [lesstif/php-jira-rest-client#280]
Right in the middle of testing this library, I started getting this error. I was successful 3 times, (I could see the 3 issues created), but now I am not getting a successful message back.

> Error Occured! CURL HTTP Request Failed: Status Code : 400, URL:https://pharmpayglobal.atlassian.net/rest/api/3/issue Error Message : {"errorMessages":[],"errors":{"description":"Operation value must be an Atlassian Document (see the Atlassian Document Format)"}}

` 

$issueField = new IssueField();

    $issueField->setProjectKey("STARTUP")
        ->setDescription("Full description for issue")
        ->setSummary("something's wrong")
        ->setPriorityName("High")
        ->setIssueType("Bug")
    ;

    $issueService = new IssueService();

    $ret = $issueService->create($issueField);

    //If success, Returns a link to the created issue.

    var_dump($ret);`

**Comment by RaXaR** [comment]
I ran into the same problem, haven't fixed the issue yet. 
Here's is a link to the [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structur), it might help you so long.

**Comment by lesstif** [comment]
i'm sorry for lately reply.

if you are JIRA Cloud users, you need to set JIRA_REST_API_V3=true in the .env file.

thanks.

**Comment by daniol** [comment]
I am experiencing the same issue with the 2.5.0 version when I try to create an issue.
I defined JIRA_REST_API_V3=true in the .env file, but I still getting the error.

**Comment by mu1f407** [comment]
@daniol I think you need to use [IssueFieldV3](https://github.com/lesstif/php-jira-rest-client/blob/master/src/Issue/IssueFieldV3.php) when using API v3. As seen in example in [readme](https://github.com/lesstif/php-jira-rest-client#create-issue-using-rest-api-v3).

**Comment by daniol** [comment]
@mu1f407 as I said, API v3 does not work because the error above comes. With v2, it works without problems.
