### ISSUE TITLE
QueryString for GET requests

### ISSUE THREAD

**Issue by Dragonqos** [lesstif/php-jira-rest-client#29]
Hello, great Job.

Will you have support of "QUERY PARAMETERS" like "expand, recent" etc?

**Comment by lesstif** [comment]
@Dragonqos yes. i have a plan, but i will be busy all next week.

**Comment by Dragonqos** [comment]
It will be great, but right now I made fork of you repo, add guzzle6 and silexServiceProvider

**Comment by lesstif** [comment]
i was fixed it. check the documentation (https://github.com/lesstif/php-jira-rest-client#get-issue-info).
