### ISSUE TITLE
Create Jira with name issue

### ISSUE THREAD

**Issue by abhigoyal1985** [lesstif/php-jira-rest-client#290]
CURL HTTP Request Failed: Status Code : 400, URL:https://vuclipdev.atlassian.net/rest/api/2/issue Error Message : {"errorMessages":[],"errors":{"assignee":"Issues must be assigned."}}

**Comment by lesstif** [comment]
An assigned field required or automatically assigned by project default settings.

if you want to allow unassigned issues,  you must turn on "Allow unassigned issues" in the Admin -> general configuration.
