### ISSUE TITLE
NoOperationMonologHandler incompatible with Monolog\Handler\AbstractProcessingHandler

### ISSUE THREAD

**Issue by a-menshchikov** [lesstif/php-jira-rest-client#292]
Since this commit (https://github.com/Seldaek/monolog/commit/06143b03e5c1598bfa6c6df65432010da0ecc28b#diff-
d1d031ebe96084844fb53eb650bc404e) NoOperationMonologHandler doesn't implement AbstractProcessingHandler correctly (doesn't return `void`). As result there is no way to set `jiraLogEnabled = false`.

I think this should be fixed ASAP.
Problem is that this breaks backward compatibility and requires PHP 7.0 in composer.json

**Comment by lesstif** [comment]
@a-menshchikov i was released new major version 2.0. 

thanks.
