### ISSUE TITLE
Remove watcher returned 401

### ISSUE THREAD

**Issue by ebarnad** [lesstif/php-jira-rest-client#293]
I try to remove a watcher using function  removeWatcher($issueIdOrKey, $watcher) but I get the following error:

CURL HTTP Request Failed: Status Code : 401, URL:https://domain/rest/api/2/issue/AKS-36941/watchers/?username=username

Remove watcher by username seem no longer supported.

I have tried to remove watcher using the accountId instead of username and it works
https://domain/rest/api/2/issue/AKS-36940/watchers/?accountId=accountId

**Comment by lesstif** [comment]
@ebarnad your PR #294 is merged.

thanks!
