### ISSUE TITLE
Add LICENSE file and file-scoped license comments into source files

### ISSUE THREAD

**Issue by a-menshchikov** [lesstif/php-jira-rest-client#296]
Now project doesn't complete Apache-2.0 fulfill the requirement for inclusion copy of the Apache License in root of project: http://www.apache.org/licenses/LICENSE-2.0#apply

To prevent license questions it should be placed in project root directory + all source files should contain comment with reference on this file.

**Comment by lesstif** [comment]
@a-menshchikov  thanks for your kindly comment.

i was created Apache License file on the root of project.
