### ISSUE TITLE
Phpstan coverage

### ISSUE THREAD

**Issue by staabm** [lesstif/php-jira-rest-client#311]
Would you accept a PR adding a travis job for phpstan?

... and additional PRs to introduce more specific typehints

This would ease usage of the lib and allow to find errors faster when using it in a upstream project

**Comment by lesstif** [comment]
hi @staabm 

thanks for your great suggestions. 

i think static code analyzer on travis job is great idea for high quality source code.

also this library  dependant to php 7.1, so to add type hint is great work too.

in conclusion i am welcome your PR.

**Comment by staabm** [comment]
cool, just wanted to get in touch with you first.

I will get a developer assigned

**Comment by trailsnail** [comment]
@lesstif 

Do you think it would be ok to define parameters a little more strict?

I was looking over the code and found an example like this: https://github.com/trailsnail/php-jira-rest-client/blob/146790c0d0c1929bcaf25a485fbde9f1c3a57527/src/Auth/AuthService.php#L47

By default I would expect, that $username is always a `string`, so why not define the method like following, according to your answer above:

> also this library dependant to php 7.1, so to add type hint is great work too.
>

```
/**
     * For internal usage. Performs login and saves session information for far cookie session authorization.
     *
     * @throws \JiraRestApi\JiraException
     * @throws \JsonMapper_Exception
     */
    public function authorizeWithCookie(string $username = '', string $password = '')
```
