### ISSUE TITLE
Not possible to make release unreleased

### ISSUE THREAD

**Issue by perviy** [lesstif/php-jira-rest-client#312]
In readme:

    // update version
    $ver->setName($ver->name . ' Updated name')
        ->setDescription($ver->description . ' Updated description')
        ->setReleased(false)
        ->setReleaseDate(
            (new \DateTime())->add(date_interval_create_from_date_string('1 months 3 days'))
        );

    $res = $versionService->update($ver);

But '->setReleased(false)' doesn't work because of \JiraRestApi\Issue\Version::jsonSerialize. It uses array_filter function that remove all entries of array that equal to FALSE. So \JiraRestApi\Issue\Version::$released is removed too.

**Comment by staabm** [comment]
reading https://docs.atlassian.com/software/jira/docs/api/REST/8.5.4/#api/2/version-updateVersion I guess the same is true for the `archived` and `overdue` properties
