### ISSUE TITLE
JSON_THROW_ON_ERROR is new in PHP 7.3, it breaks backwards compatibility with older PHP versions 

### ISSUE THREAD

**Issue by droath** [lesstif/php-jira-rest-client#314]
### Problem / Motivation

There are numerous areas in the codebase where the JSON_THROW_ON_ERROR constant is used, but it's only valid in PHP 7.3+. Currently it looks like you have support for PHP 7.1+ which this will error out with the following:

`json_decode() expects parameter 4 to be integer, string given in /var/www/vendor/lesstif/php-jira-rest-client/src/Board/BoardService.php on line 41`

**Comment by lesstif** [comment]
@droath thanks for your contribution.

i was fixed your suggestion at this time.

could your test master branch running correctly on your environment.

thanks!
