### ISSUE TITLE
IssueField - some fields can be null

### ISSUE THREAD

**Issue by leuchtdiode** [lesstif/php-jira-rest-client#32]
Thanks for the great API. Unfortunately I experienced some problems with the search-Call from IssueService.

It appears that many fields can be null, but they are not declared as nullable in the IssueField.php class. I found these: description, environment, resolution, aggregatetimespent, timeestimate, aggregatetimeoriginalestimate, resolutiondate, aggregatetimeestimate, lastViewed, timeoriginalestimate

Therefore JsonMapper is throwing an exception.

**Comment by lesstif** [comment]
thanks for your comment.

Recently dev-master version applied nullable field, but is not released yet.
i was released 1.7.0 a little while ago.

You can specify the exact version of a this library to '^1.7.0'.

**Comment by leuchtdiode** [comment]
Thank you very much.
