### ISSUE TITLE
How to get data type from a project?

### ISSUE THREAD

**Issue by devweb99** [lesstif/php-jira-rest-client#334]
$p = $proj->get('TECHSUP'); 
there is the right type, I don’t understand how to get data from it

**Comment by lesstif** [comment]
ProjectService class get method returning \JiraRestApi\Project\Project model class.

you can access project data(for example, projectCategory, versions, etc..) through Project model's public property, see below.

```php
$proj = new ProjectService();

$p = $proj->get('TECHSUP');

var_dump($p->name);
var_dump($p->description);
var_dump($p->lead);
```
