### ISSUE TITLE
Move projects with customfields between instances where ids are different causes conflicts between config file.

### ISSUE THREAD

**Issue by VickWard** [lesstif/php-jira-rest-client#341]
I have custom fields that are referenced by 'php-jira-rest-client'.  The code uses a config file that contains a list of the custom field id's.  When I migrate between instances we need to update the config file with the correct custom field id which has caused migration issues in the past.  

Is there a way to reference custom fields other than the id or cfname?  I thought perhaps the cfkey, but cannot find any reference to this field and am not sure what it is used for.  The value is null in all of my custom fields in each instance.

Any assistance or recommendations much appreciated.

**Comment by lesstif** [comment]
hi @VickWard 

unfortunately, i don't know what this means cfkey field and i can't found documentation.

i thank that third party custom field plugin will be help to you, for example [customfield editor for jira](https://marketplace.atlassian.com/apps/1212096/customfield-editor-for-jira).

thanks.!
