### ISSUE TITLE
Error: Call to undefined method Monolog\\Logger::addInfo

### ISSUE THREAD

**Issue by psycohomer** [lesstif/php-jira-rest-client#343]
When attempting to run the remove watcher method of IssueService I am now getting this error. Using an older version of either this repo or monolog does not produce the same error. 

PHP Fatal error:  Uncaught Error: Call to undefined method Monolog\\Logger::addInfo()
JiraRestApi\\Issue\\IssueService->removeWatcher('XXXX-10402', 'CRMMTO_Service')

**Comment by lesstif** [comment]
hi @psycohomer 

it's fixed in the ver 2.2.2.

thanks!

**Comment by psycohomer** [comment]
Thank you so much for the fast turn.
