### ISSUE TITLE
Getting worklogs for a period

### ISSUE THREAD

**Issue by maartendeblock** [lesstif/php-jira-rest-client#347]
Is there a way to get worklogs of a certain period?

Examining the code, I expected a WorklogService like there is a IssueService and a UserService.

What am I missing?

**Comment by lesstif** [comment]
hi @maartendeblock.

currently, there is no service class.

But by combining the JQL and worklog methods you can do what you want, see below.

```php
// search previous year's worklog.
 worklogDate >= startOfYear(-1)   and worklogDate <= endOfYear(-1) ;

        try {
            $issueService = new IssueService();

            $IssueSearchResult = $issueService->search($jql);

            foreach ($IssueSearchResult->getIssues() as $issue) {
                $pwl = $issueService->getWorklog($issue->key);

                $worklogs = $pwl->getWorklogs();
                var_dump($worklogs);
            }
        } catch (JiraException $e) {
            $this->assertTrue(false, 'testSearch Failed : '.$e->getMessage());
        }
```

**Comment by maartendeblock** [comment]
Thank you for the answer. But wouldn't this return all worklogs of the related messages and not just the ones in the requested period?

**Comment by lesstif** [comment]
if you adjust the period of JQL, I think you will get the desired result. 

could you try it and share the results please?

**Comment by gabrielmdu** [comment]
@maartendeblock was right. I just tested a JQL with `worklogDate > :date` field and it returned the issues with all the worklogs, even the ones before the worklogDate.

I think the only way is filtering the worklogs array after the result is returned.
