### ISSUE TITLE
Incompatible with Laravel 8

### ISSUE THREAD

**Issue by wsdnathan** [lesstif/php-jira-rest-client#348]
Change this composer.json requirement so it works with future phpdotenv versions like 5.0 since every time Laravel updates it causes a conflict with your package and your requirement basically says to require any version except for the latest one which is counterproductive:
    "require": {
        "vlucas/phpdotenv": "~1.0|~2.0|^3.0|^4.0"

**Comment by lesstif** [comment]
i's fixed at [v-2.4.0|https://github.com/lesstif/php-jira-rest-client/releases/tag/2.4.0].

thanks.
