### ISSUE TITLE
Class '\JiraRestApi\Issue\$name' not found

### ISSUE THREAD

**Issue by anikgoel** [lesstif/php-jira-rest-client#35]
I am using IssueService search function with JQL "project=XYZ" and when result is coming it is giving me below error - 

```
FatalErrorException in JsonMapper.php line 488:
Class '\JiraRestApi\Issue\$name' not found
```

Can anyone tell me why it would have been happening?

**Comment by anikgoel** [comment]
I have done some debugging, it is coming due to class not found for function `setIssueType` in IssueField.php

**Comment by anikgoel** [comment]
for `setIssueType` function comment added is - 
```
/**
     * set issue type
     *
     * @param $name string
     *
     * @return $this
     */
```

where `$name` type is added after `$name` which is causing the issue

**Comment by lesstif** [comment]
@anikgoel Great thanks,!
