### ISSUE TITLE
[Request] IssueType Management

### ISSUE THREAD

**Issue by RaXaR** [lesstif/php-jira-rest-client#351]
Hello, I tried to create a new Issue on an existing Project but couldn't because the IssueType is rejected by the API.
I tried both a new IssueType object as well as a string.
```
CURL HTTP Request Failed: Status Code : 400, URL:https://<host_name_removed>.atlassian.net/rest/api/2/issue
Error Message : {"errorMessages":[],"errors":{"issuetype":"The issue type selected is invalid."}}
```

I scrolled through the source code for this plugin but saw that there isn't a section specifically for IssueTypes yet.
Here is the [JIRA API documentation regarding IssueTypes](https://docs.atlassian.com/software/jira/docs/api/REST/8.12.2/#api/2/issuetype).

**Could this possibly be implemented?**

**Comment by lesstif** [comment]
hi @RaXaR 

you could reach out issueType field using setIssueType method like below.

```php
 $issueField = new IssueField();

    $issueField->setProjectKey("TEST")
                ->setSummary("something's wrong")
                ->setAssigneeName("lesstif")
                ->setPriorityName("Critical")
                ->setIssueType("Bug");
```

i guess from the server's response error message, it seems to be occurred by  invalid issue type string.

if you are using localization jira instance, check issue type string is translated.

**Comment by RaXaR** [comment]
Hi @lesstif thanks for the response.

I have since discovered that there is a whole string of issue with our setup. One of which is that the user we used to connect to the JIRA API does not have proper permissions to create issues. 

I think I'm going to close this ticket, still, thank you very much for the assistance.
