### ISSUE TITLE
In recent Dotenv versions `getenv()` is discouraged.

### ISSUE THREAD

**Issue by wivaku** [lesstif/php-jira-rest-client#352]
In recent Dotenv versions `getenv()` is discouraged.
https://github.com/vlucas/phpdotenv#putenv-and-getenv

The current code relies on `getenv()`:
https://github.com/lesstif/php-jira-rest-client/blob/f4d872daeb9af30d6bb000a4add245f23e920f25/src/Configuration/DotEnvConfiguration.php#L56

Should be `$_ENV[$key]` instead.

_Originally posted by @wivaku in https://github.com/lesstif/php-jira-rest-client/issues/319#issuecomment-703747954_

**Comment by wivaku** [comment]
BTW. the mentioned `Dotenv::createUnsafeImmutable()` did not seem to work as workaround for existing `getenv()`.

**Comment by lesstif** [comment]
@wivaku thanks!
