### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by robguida** [lesstif/php-jira-rest-client#353]
I have integrated php-jira-rest-client with my project, and everything was working at one point. But I believe some requirements have changed. I am now getting these errors:

` JiraRestApi\\JiraException Object
                                        (
                                            [message:protected] => CURL HTTP Request Failed: Status Code : 400, URL:https://pharmpayglobal.atlassian.net/rest/api/2/issue
Error Message : {"errorMessages":[],"errors":{"summary":"Field 'summary' cannot be set. It is not on the appropriate screen, or unknown.","description":"Field 'description' cannot be set. It is not on the appropriate screen, or unknown.","priority":"Field 'priority' cannot be set. It is not on the appropriate screen, or unknown."}}
                                            [string:Exception:private] => 
                                            [code:protected] => 400
                                            [file:protected] => /var/www/PharmPay/Service/vendor/lesstif/php-jira-rest-client/src/JiraClient.php
                                            [line:protected] => 264
                                            [trace:Exception:private] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [file] => /var/www/PharmPay/Service/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php
                                                            [line] => 78
                                                            [function] => exec
                                                            [class] => JiraRestApi\\JiraClient
                                                            [type] => ->
                                                            [args] => Array
                                                                (
                                                                    [0] => /issue
                                                                    [1] => {"fields":{"summary":"Exception caught in the API","issuetype":{"name":"Bug"},"description":"\
h1. Error\
`

Any clue what I am doing wrong?

Thanks,
R

**Comment by lesstif** [comment]
hi @robguida 

i guess that it seems like screen or workflow scheme error.

check your login account's permission or project permission or project screen scheme please.

thanks.
