### ISSUE TITLE
Gett All Issues from Project

### ISSUE THREAD

**Issue by jonathansigg** [lesstif/php-jira-rest-client#357]
if i do `$proj = new ProjectService(); $p = $proj->get('MyProject');`

I get a Object with all projects. How can i List all issues in each component?

**Comment by lesstif** [comment]
hi @jonathansigg 

if you want to get all issues from components, you will use JQL(Jira query language).

check out jql example here(https://github.com/lesstif/php-jira-rest-client#perform-an-advanced-search)

thanks.
