### ISSUE TITLE
Specified user does not exist or you do not have required permissions

### ISSUE THREAD

**Issue by skione** [lesstif/php-jira-rest-client#358]
This is if GDPR strict mode is enabled and for Cloud implementations it is. You need to replace using the username with accountId. I tested it with addUserToGroup and it worked.

Changed line 101 in Group/GroupService.php

from:
$data = json_encode(['name' => $userName]);

to:
$data = json_encode(['accountId' => $userName]);

However for any implementations the access username or name and have strict mode enabled this code doesn't work beyond authentication.

**Comment by lesstif** [comment]
hi @skione 

thanks you your information.

i will be to rewrite this library for JIRA Cloud,  and i don't forget your great suggestion at that time.
