### ISSUE TITLE
Service desk API support?

### ISSUE THREAD

**Issue by AlexP11223** [lesstif/php-jira-rest-client#359]
Looks like only adding comments is supported now, or did I miss something? https://github.com/lesstif/php-jira-rest-client/blob/master/src/Request/RequestService.php

I need to get/create requests: https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-request/#api-rest-servicedeskapi-request-post

Also it seems a bit dangerous for future-proofness that this `Request` is in the root namespace. What if there is another Request in some other part of API? I think it should be in `JiraRestApi\ServiceDesk\Request` namespace.

**Comment by lesstif** [comment]
hi @AlexP11223 

I don't use JIRA Service Desk and that file is a merged from the PR, so sorry i don't know this code working correctly.

BTW  it is very reasonable that you commented the dangers of name space.

so i think it should move into the _JiraRestApi\ServiceDesk_ namespace too. 

i will be rename namespace at next release.

thanks.

**Comment by AlexP11223** [comment]
> i will be rename namespace at next release.

If it is not a [major](https://semver.org/) release (3.0.0) you should not just rename it because it will break compatibility. Maybe mark it as deprecated and create a copy in the correct place.

**Comment by lesstif** [comment]
@AlexP11223 

ok good point, i will be follow the semantic versioning too.

thanks.
