### ISSUE TITLE
Cannot create sub tasks in Next-Gen projects

### ISSUE THREAD

**Issue by kategee** [lesstif/php-jira-rest-client#360]
When trying to create a subtask (which works fine on other boards), the script fails when trying to create sub task on a task that belongs to the next-gen jira board:

```php
$issueField = new IssueField();

$issueField->setProjectKey("XX")
           ->setSummary("something's wrong")
           ->setIssueType("Sub-task")  //issue type must be Sub-task
           ->setParentKeyOrId('XX-123')  //Issue Key
;

$issueService = new IssueService();
$ret = $issueService->create($issueField);
```

Error returned: 

```
CURL HTTP Request Failed: Status Code : 400, URL:https://myproject.atlassian.net/rest/api/3/issue
Error Message : {"errorMessages":[],"errors":{"issuetype":"issue type is required"}}
```

**Comment by lesstif** [comment]
hi @kategee 

i 'm tried various test, i got the jira cloud seem to throw confusing error message.

because error message means issue type value is null, but situation is unknown issue type.

if you are not english version's jira user, could you try replace 'Sub-Task' to translated word.

for example in korean version jira , i 'm 'Sub-Task' replace to '하위 작업' that i got the successful result.

![image](https://user-images.githubusercontent.com/404534/98503617-51579600-2298-11eb-96b2-571754dc1f49.png)

**Comment by lesstif** [comment]
it's example code.

```php
<?php
            $issueField = new IssueField();

            $issueField->setProjectKey('TEST')
                ->setSummary("something's wrong")
                ->setAssigneeName('lesstif')
                ->setPriorityName('High')
                ->setIssueType('하위 작업')  //issue type must be Sub-task
                ->setParentKeyOrId('TEST-1')  //Issue Key
            ;

            $issueService = new IssueService();

            $ret = $issueService->create($issueField);
```

**Comment by kategee** [comment]
@leststif I am on English version of Jira, I updated `setIssueType` but i still get the same error.

` $issueField->setProjectKey($projectId)
                    ->setSummary($title)
                    ->setDescription("Full description for issue")
                    ->setIssueType("Sub-Task") 
                    ->setParentKeyOrId($parentIssueId)
                ;`

I still get:

`Error Message : {"errorMessages":[],"errors":{"issuetype":"issue type is required"}}`

**Comment by lesstif** [comment]
@kategee could you get the all project issue types via below code.

```php
$proj = new ProjectService();

$p = $proj->get('TEST');
var_dump($p);
```

you should find the issue field name which subtask is true from result array, for example see below my jira project dump result.

finally you could use this issue type name as sub-task Type string, in this example i'm using '하위 작업' as subtask type name.

![image](https://user-images.githubusercontent.com/404534/98618145-e06db800-2343-11eb-8d2d-4a24229cd286.png)

**Comment by kategee** [comment]
@lesstif here it is: looks like it's all one word.
```
object(JiraRestApi\Issue\IssueType)#52 (8) {
      ["self"]=>string(57) "https://xxx.atlassian.net/rest/api/3/issuetype/10852"
      ["id"]=>string(5) "10852"
      ["description"]=>string(36) "Subtasks track small pieces of work."
      ["iconUrl"]=>string(96) "https://xxx.atlassian.net/secure/viewavatarsize=medium&avatarId=10316&avatarType=issuetype"
      ["name"]=>string(7) "Subtask"
      ["subtask"]=>bool(true)
      ["statuses"]=>NULL
      ["avatarId"]=>int(10316)
    }
```

**Comment by lesstif** [comment]
@kategee 

replace  '**Sub-task**' to '**Subtask**' and rerun code.

```php
$issueField = new IssueField();

    $issueField->setProjectKey("XX")
                ->setSummary("something's wrong")
                ->setIssueType("Subtask")  //issue type must be Sub-task
                ->setParentKeyOrId('XX-123')  //Issue Key
    ;

    $issueService = new IssueService();
    $ret = $issueService->create($issueField);
```

**Comment by lesstif** [comment]
@kategee  ok great!

**Comment by kategee** [comment]
@lesstif Thanks for your help, so weird they would change it for the next-gen projects...
