### ISSUE TITLE
use setUntranslatedName gives error while setTransitionName works but not with locales

### ISSUE THREAD

**Issue by mrooseboom** [lesstif/php-jira-rest-client#380]
I updated to the lastest version and used setTransitionName but that gives a lot of issues when the user changes its locale. The doc mentions to use setUntranslatedName in that case but once I use that method I get this error:

Error Message : {"errorMessages":["Issue does not exist or you do not have permission to see it."],"errors":{}}PHP Fatal error:  Uncaught Dotenv\Exception\ValidationException: One or more environment variables failed assertions: JIRA_HOST is missing, JIRA_USER is missing, JIRA_PASS is missing. in /var/www/app/vendor/vlucas/phpdotenv/src/Validator.php:175
Stack trace:
#0 /var/www/app/vendor/vlucas/phpdotenv/src/Validator.php(57): Dotenv\Validator->assert(Object(Closure), 'is missing')
#1 /var/www/app/vendor/vlucas/phpdotenv/src/Dotenv.php(253): Dotenv\Validator->required()
#2 /var/www/app/vendor/lesstif/php-jira-rest-client/src/Configuration/DotEnvConfiguration.php(144): Dotenv\Dotenv->required(Array)
#3 /var/www/app/vendor/lesstif/php-jira-rest-client/src/Configuration/DotEnvConfiguration.php(19): JiraRestApi\Configuration\DotEnvConfiguration->loadDotEnv('../')
#4 /var/www/app/vendor/lesstif/php-jira-rest-client/src/JiraClient.php(87): JiraRestApi\Configuration\DotEnvConfiguration->__construct('../')
#5 /var/www/app/vendor/lesstif/php-jira-rest-client/src/Issue/IssueService.php(1231): JiraRestApi\JiraClient->__construct()
#6 /var/www/a in /var/www/app/vendor/vlucas/phpdotenv/src/Validator.php on line 175

**Comment by lesstif** [comment]
hi @mrooseboom 

your log messages looks like that property settings errors, for example you need setting JIRA_HOST, JIRA_USER, JIRA_PASS variable correctly.

could you check your .env file please?

**Comment by mrooseboom** [comment]
I use the array variant:

`$arrayconfig = new ArrayConfiguration(
			array (
				'jiraHost'     => $jirahost,
				'jiraUser'     => $jirausername,
				'jiraPassword' => $jiratoken
			)
		);
$issueService = new IssueService($arrayconfig);`

I never used the .env file at all. Now only while I want to use another method it seems only available with env?

**Comment by lesstif** [comment]
Looking at your code, it looks like you called DotEnvConfiguration.
could you show the whole source code to me?

**Comment by mrooseboom** [comment]
This is the code that works:

`<?php

require __DIR__.'/../vendor/autoload.php';

use JiraRestApi\Configuration\ArrayConfiguration;
use JiraRestApi\JiraException;
use JiraRestApi\Issue\IssueService;
use JiraRestApi\Field\Field;
use JiraRestApi\Issue\IssueField;
use JiraRestApi\Field\FieldService;
use JiraRestApi\Issue\Transition;
use JiraRestApi\Issue\TimeTracking;

$username = "mine@gmail.com";
$token = "somekey";

$arrayconfig = new ArrayConfiguration(
	array(
		'jiraHost' => 'https://subomdain.atlassian.net/',
		'jiraUser' => $username,
		'jiraPassword' => $token
	)
);

$issueService = new IssueService($arrayconfig);
$transition = new Transition();

$doc['Name'] = "test script";
$doc['Description'] = "bla bla";
$assigneeName = "";
$doc['jiraEpic'] = "";
$doc['StorySize'] = "";
$jiraId = "DEV-16";
$type = "story";
$storyParentId = "";
$jiraState = "To do";

try
{
	$issueField = new IssueField(true);

	$issueField->setSummary(urldecode($doc['Name']));
	$issueField->setDescription(urldecode($doc['Description']));
	$issueField->setAssigneeName($assigneeName);
	//$issueField->addCustomField('customfield_10011', $doc['Name']);

	if ($type == "Story" && $doc['jiraEpic'] != "")
	{
		$issueField->addCustomField('customfield_10014', $doc['jiraEpic']);
	}
	if ($type == "Story" && $doc['StorySize'] != "")
	{
		$issueField->addCustomField('customfield_10023', $doc['StorySize']);
	}
	if ($type == "Task")
	{
		$issueField->setParentKeyOrId($storyParentId);
	}

	// optionally set some query params
	$editParams = [];

	// update issuefields
	$issueService->update($jiraId, $issueField, $editParams);
}
catch (JiraException $e)
{
	echo "\nERROR UPDATING ISSUE (" . $type . ") TO JIRA:\n";
	print_r($e->getMessage());
}


try
{
	// update state
	if ($jiraState != "")
	{
		$transition = new Transition();
		$transition->setTransitionName($jiraState);
		$issueService->transition($jiraId, $transition);
	}

}
catch (JiraException $e)
{
	echo "\nERROR TRANSITION STATE (" . $type . ") TO JIRA:\n";
	print_r($e->getMessage());
}`


and if I change the line:
$transition->setTransitionName($jiraState);
to
$transition-> setUntranslatedName($jiraState);
I get this error

**Comment by lesstif** [comment]
hi @mrooseboom .
thanks for your contribution,so  i can fixed bug in v2.5.1(https://github.com/lesstif/php-jira-rest-client/releases/tag/2.5.1)

thanks!.

**Comment by mrooseboom** [comment]
great! thanks for the quick response

**Comment by mrooseboom** [comment]
I do get some Jira errors with the new version when using the setUntranslatedName

ERROR TRANSITION STATE (Story) TO JIRA: CURL HTTP Request Failed: Status Code : 400, URL:https://domain.atlassian.net//rest/api/2/issue/DEV-17/transitions
Error Message : {"errorMessages":["Transition id '3' is not valid for this issue."],"errors":{}}
11:41
ERROR TRANSITION STATE (Story) TO JIRA: CURL HTTP Request Failed: Status Code : 400, URL:https://domain.atlassian.net//rest/api/2/issue/DEV-17/transitions
Error Message : {"errorMessages":["Transition id '10001' is not valid for this issue."],"errors":{}}
11:43
ERROR TRANSITION STATE (Story) TO JIRA: CURL HTTP Request Failed: Status Code : 400, URL:https://domain.atlassian.net//rest/api/2/issue/DEV-17/transitions
Error Message : {"errorMessages":["Transition id '10005' is not valid for this issue."],"errors":{}}

when I look at the url Jira provides valid id's are 11 (To Do), 21 (In Progress), 31 (Done),41 (blocked), 51 (review) and 61 (test). Do I need to use these id's or the names of the ids?
I don't know where Transition id '3' or Transition id '10001' or Transition id '10005' come from, I use the actual names
