### ISSUE TITLE
Bug: get Exception (http-code 302) if the jira file as a redirect_url in response 

### ISSUE THREAD

**Issue by srhinow** [lesstif/php-jira-rest-client#384]
![jira-client-attachment-issue](https://user-images.githubusercontent.com/741418/115232560-23b02c00-a117-11eb-92ab-1bae963f9665.png)

with this code:
``
$atts = new AttachmentService(new ArrayConfiguration(
    array(
        'jiraHost' => $objApi->jiraHost,
        // for basic authorization:
        'jiraUser' => $objApi->jiraUser,
        'jiraPassword' => $objApi->jiraPassword,
    )
));
$att = $atts->get($attachment['id'], $documentFolder, $overwrite = true);
```

**Comment by srhinow** [comment]
is it possible that I can set a parameter that forces the "CURLOPT_FOLLOWLOCATION" => true?
Because if I change (comment out) the code in JiraClient :: download () code as follows:
``
          // curl_setopt (): CURLOPT_FOLLOWLOCATION cannot be activated if an open_basedir is set
// if (! function_exists ('ini_get') ||! ini_get ('open_basedir')) {
              curl_setopt ($ ch, CURLOPT_FOLLOWLOCATION, true);
//}
``
then it works successfully for me without errors.

**Comment by lesstif** [comment]
@srhinow yes you can do it, by the way do you to set open_basedir in the php.ini? 

this flag has very critical security issue, so you need to carefully  when using this setting.
