### ISSUE TITLE
Handle rate limiting response headers

### ISSUE THREAD

**Issue by geryguilbon** [lesstif/php-jira-rest-client#388]
According to this documentation we can sometimes be confronted to Rate Limiting
[https://developer.atlassian.com/cloud/jira/platform/rate-limiting/](https://developer.atlassian.com/cloud/jira/platform/rate-limiting/)

Is it possible to add a feture which could allow us to retrieve the headers response so that we can handle this issue ?

**Comment by lesstif** [comment]
hi @geryguilbon 
i am always welcome to your contribution.

thanks.
