### ISSUE TITLE
Unable to set custom field value for string type

### ISSUE THREAD

**Issue by sachinbhosale1191** [lesstif/php-jira-rest-client#389]
I have tried to update and add text to the following string type custom field "addCustomField('customfield_10100', 'text area body text')" for API V3, it is returning the following error

"CURL HTTP Request Failed: Status Code : 400, URL:https://xxxxx.atlassian.net//rest/api/3/issue/test-8?notifyUsers=0\nError Message : {\"errorMessages\":[],\"errors\":{\"customfield_10100\":\"Operation value must be an Atlassian Document (see the Atlassian Document Format)\",\"customfield_10101\":\"Operation value must be an Atlassian Document (see the Atlassian Document Format)\"}}"

**Comment by lesstif** [comment]
according to the atlassian's documents, rich text stored in ADF(Atalssian Document format), for example comment or description field.

so you should formatting text field for ADF.
