### ISSUE TITLE
Error on getAllProjects example

### ISSUE THREAD

**Issue by rogercastaneda** [lesstif/php-jira-rest-client#4]
Getting error on getAllProjects example:
Error Occured! JsonMapper::map() requires first argument to be an object, array given.

**Comment by rogercastaneda** [comment]
Working now!.

**Comment by rogercastaneda** [comment]
second parameter in line 24 in ProjectService.php should be false:
json_decode($ret, true), new \ArrayObject(), '\JiraRestApi\Project\Project'
-> 
json_decode($ret, false), new \ArrayObject(), '\JiraRestApi\Project\Project'

**Comment by lesstif** [comment]
fixed on https://github.com/lesstif/php-jira-rest-client/commit/262c4be87db92ac7a09f20fec29fdc71f986319d
