### ISSUE TITLE
Bearer vs Basic Authentication with token

### ISSUE THREAD

**Issue by jescampos** [lesstif/php-jira-rest-client#419]
Hi, maybe I did some bad configuration, but I just made it working changing the JiraClient.php on line 517 
- from:
$curl_http_headers[] = 'Authorization: Bearer ' . $this->getConfiguration()->getPeronalAccessToken();

- to:
$curl_http_headers[] = 'authorization: Basic '. base64_encode($this->getConfiguration()->getJiraUser() . ':' . $this->getConfiguration()->getPeronalAccessToken()

**Comment by lesstif** [comment]
Hi @jescampos Sorry for the late reply.

You're Jira Instance looks very old version, so it doesn't support token-based authentication.

**Comment by jescampos** [comment]
But I'm using jira cloud.... Jira cloud is not automatically updated?

**Comment by lesstif** [comment]
Jira cloud is always up to date, did you set this line in the .env configuration?

```
TOKEN_BASED_AUTH=true
```

**Comment by lesstif** [comment]
Hi @jescampos You're right!

JIRA Cloud v3 supports Basic auth, so I fixed it.

Thank you!

**Comment by jescampos** [comment]
Thank you :)

**Comment by nsrosenqvist** [comment]
@lesstif This fix appears to have been reverted, why is that? I need the changes of https://github.com/lesstif/php-jira-rest-client/commit/91c754e8b18501ece07bc1dc878a056c1200bbf0 to be able to connect this way against Jira Cloud.
