### ISSUE TITLE
Unable to read the environment file at ../.env.

### ISSUE THREAD

**Issue by reardestani** [lesstif/php-jira-rest-client#42]
In Heroku I have this issue. It's works fine in local server but in Heroku it does not load environment variables.

Any experience with this issue in Heroku?

I am using this package in Lumen from Laravel.

**Comment by lesstif** [comment]
I haven't experience deployed on the heroku yet but you can use alternative app configuration with ArrayConfiguration class.

```php
use JiraRestApi\Configuration\ArrayConfiguration;

$iss = new IssueService(new ArrayConfiguration(
          array(
               'jiraHost' => 'https://your-jira.host.com',
               'jiraUser' => 'jira-username',
               'jiraPassword' => 'jira-password',
          )
   ));
```

**Comment by reardestani** [comment]
Thanks for letting me. Please mention this in the docs. But it gives following error.

<img width="538" alt="screenshot at aug 04 19-08-28" src="https://cloud.githubusercontent.com/assets/2968507/17406071/416563a0-5a77-11e6-923a-d2076babc9b4.png">

**Comment by lesstif** [comment]
@reardestani i was fixed at https://github.com/lesstif/php-jira-rest-client/commit/21d0fbb48e402cd484a58f6a76e7a527a9b3147a. check out it and feed back please.

**Comment by reardestani** [comment]
It gives error and I start to use Guzzle directly. Thanks for your package.
