### ISSUE TITLE
Set value for radio button custom field 

### ISSUE THREAD

**Issue by voltan** [lesstif/php-jira-rest-client#424]
Hello

I need to create an issue by one radio button, First I create a radio button as a custom field, but I can not set the value/option in creation, after that I try to add value when I create an issue, but it has an error

```
{"errorMessages":[],"errors":{"customfield_10035":"Specify a valid 'id' or 'name' for MyCustomFieldName"}}
```

another question, How I can add my new custom field to issue the appropriate screen?

Thanks

**Comment by lesstif** [comment]
Hi @voltan, Thank you for reaching out to me.

Unfortunately, This project doesn't support set custom fields when an Issue creates or modify.

Additionally, always I'm welcome any PR.
