### ISSUE TITLE
New feature: get Project Components

### ISSUE THREAD

**Issue by edegaudenzi** [lesstif/php-jira-rest-client#426]
Functionality to retrieve Components defined in a Jira project is missing.

Something like:
```
$proj = new ProjectService();
$prjs = $proj->getAllProjects();
// Extract and show Project Components for every Jira Project
foreach ($prjs as $p) {
    var_export($proj->getProjectComponents($p->id));
}
```

I'll try to create a pull request about this.

**Comment by lesstif** [comment]
Hi @edegaudenzi, I'm looking forward to your PR.

**Comment by edegaudenzi** [comment]
Hi @lesstif , you're more than welcome. I think PR's up.

**Comment by lesstif** [comment]
Hi @edegaudenzi , Thank you for your great PR.
Could you update README.md with sample code, please?

**Comment by edegaudenzi** [comment]
It should already be in the first commit. I've tried to follow existing code style and naming convention but will definitely need your review! ;)
