### ISSUE TITLE
Potentially rename env vars that are missing JIRA_ prefix

### ISSUE THREAD

**Issue by mimarcos** [lesstif/php-jira-rest-client#431]
Is there any reason that the following env vars are missing the JIRA prefix?

```
TOKEN_BASED_AUTH=true
PERSONAL_ACCESS_TOKEN="your-access-token-here"
# to enable session cookie authorization
# COOKIE_AUTH_ENABLED=true
# COOKIE_FILE=storage/jira-cookie.txt
# if you are behind a proxy, add proxy settings
PROXY_SERVER="your-proxy-server"
PROXY_PORT="proxy-port"
PROXY_USER="proxy-username"
PROXY_PASSWORD="proxy-password"
```

Would you be amenable to a PR that updates these to look for, for example, either `JIRA_PERSONAL_ACCESS_TOKEN` or `PERSONAL_ACCESS_TOKEN` so our app env files don't lack namespacing of said variables?

**Comment by lesstif** [comment]
Hi @mimarcos, 
There is no particular reason to exclude some variables from ENV, except that I didn't use them. :)

If you create a PR, I will merge it into the main branch. 

Thank you!

**Comment by lesstif** [comment]
Fixed at https://github.com/lesstif/php-jira-rest-client/releases/tag/4.0.0
