### ISSUE TITLE
PHP 8.1 Support - Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated

### ISSUE THREAD

**Issue by nsmith520** [lesstif/php-jira-rest-client#435]
The JiraClient `authorization` method takes an optional parameter `$cookieFile`, which is defaulted to null. There is a conditional `if(!file_exists($cookieFile))` that will throw an error exception with PHP 8 when the parameter is null.

`Deprecated: file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated`

**Comment by lesstif** [comment]
Hi @nsmith520 Thank you for reaching out to me.

IMO, the code checks the $cooieFile variable is string before the _file_exist_ method.
Could you get a chance to review the below code, please?

[code](https://github.com/lesstif/php-jira-rest-client/blob/ea87472fae5988a9f6253bae08b08c5cb134a579/src/JiraClient.php#L477)
