### ISSUE TITLE
Class "Monolog\Level" not found

### ISSUE THREAD

**Issue by yusufalper** [lesstif/php-jira-rest-client#441]
Laravel 9

when i define

           ` $issueService = new IssueService();`

it throws error like this.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/17886290/173581464-70530b52-bc3b-40ba-95dc-ffb24e45d901.png">

**Comment by wsslfnstr** [comment]
I have the same issue with the ProjectService

**Comment by mmenguy-vu** [comment]
Same one here too

**Comment by lesstif** [comment]
I'm sorry, Monolog\Level was introduced to monolog 3.0, so you need to your dependency update.

```bash
composer update monolog/monolog
```

I'll change the dependency config for monolog in the composer.json.

**Comment by yusufalper** [comment]
Error on laravel 9 again.

spatie/ignition requires monolog/monolog 2.0.


- You can only install one version of a package, so only one of these can be installed: monolog/monolog[2.0.0-beta1, ..., 2.x-dev, 3.0.0-RC1, 3.0.0, 3.1.0, 3.x-dev].
    
I think 
        "monolog/monolog": "^2.0|^3.0",
or something like that will solve the problem, if you can update..

**Comment by lesstif** [comment]
Hi @yusufalper I had dropped the monolog v3 dependent code.
Could you check that your problem is solved?

**Comment by yusufalper** [comment]
still same @lesstif. 

"lesstif/php-jira-rest-client 4.0.2 requires monolog/monolog ^3.0 ".

I had to downgrade php-jira-rest-client to ^3.1

3.1.1 version works perfect.

**Comment by yusufalper** [comment]
Manuel update worked man, thanks. @lesstif

**Comment by lesstif** [comment]
Thank you for your check @yusufalper.
Ok, I'll release a new version and then you need to change your dependency as below.

```javascript
"require": {
   "lesstif/php-jira-rest-client": "dev-main"
 }
```
