### ISSUE TITLE
Trait "JiraRestApi\AgileApiTrait" not found

### ISSUE THREAD

**Issue by wsslfnstr** [lesstif/php-jira-rest-client#442]
When i try to use the example to get all my boards it throws an error.

>      try {
>             $board_service = new BoardService();
>             $board = $board_service->getBoardList();
> 
>             var_dump($board);
>         } catch (JiraRestApi\JiraException $e) {
>             print('Error Occured! ' . $e->getMessage());
>         }
>         

        Trait "JiraRestApi\AgileApiTrait" not found
        
Did i miss something?

**Comment by davidmonnom** [comment]
Hi you can add a file in src at root with

`<?php

namespace JiraRestApi;

trait AgileApiTrait
{
    private function setupAPIUri($version = '1.0')
    {
        $this->setAPIUri('/rest/agile/'.$version);
    }
}
`

**Comment by lesstif** [comment]
Hi @wsslfnstr, I'm sorry, It's my mistake.
I pushed commit, Could you check out, please.
