### ISSUE TITLE
AddCustomField value type should not be restricted to string

### ISSUE THREAD

**Issue by enduro44** [lesstif/php-jira-rest-client#453]
https://github.com/lesstif/php-jira-rest-client/blob/46ed86a8ab017bfc71d39fc0d26a7105a9c77e8a/src/Issue/IssueField.php#L153  
There are cases when custom field value is expected to be a number. In this case JIRA API will return 400, e.g. `{"errorMessages":[],"errors":{"customfield_10832":"Operation value must be a number"}}`

Maybe we can use mixed instead?
`public function addCustomField(string $key, mixed $value): static`

**Comment by ricksoons** [comment]
I have already created a PR for this issue: #451 

You could argue if `mixed` or `string|int` is better.

**Comment by enduro44** [comment]
> I have already created a PR for this issue: #451
> 
> You could argue if `mixed` or `string|int` is better.

I agree, but then it should be string|int|float.

**Comment by ricksoons** [comment]
Alright that makes sense; let me adjust the PR

**Comment by lesstif** [comment]
I just merged it. Thank you!
