### ISSUE TITLE
JSON property "description" in class "JiraRestApi\Issue\IssueFieldV3" is an object and cannot be converted to a string

### ISSUE THREAD

**Issue by Pequem** [lesstif/php-jira-rest-client#454]
Jira can send a descriptionV3 field in description key of json and this break the Lib.

![image](https://user-images.githubusercontent.com/11294736/176499298-1a0cbbbf-23d8-43f9-a882-86e76bb6923f.png)

**Comment by lesstif** [comment]
Hi, @Pequem I'm sorry for the late reply.

I changed it on this [commit](https://github.com/lesstif/php-jira-rest-client/commit/525761db73ba9b832438a3b8016beb78f83cef51).

Could you check the works well?

**Comment by hadesunseenn** [comment]
getting the same error when performing search 
$ret = $issueService->search($query);

**Comment by russclewett-mw** [comment]
If this helps anyone, I was getting this error until I realised I was still running 4.x, upgraded to 5.x and its all sorted now.
