### ISSUE TITLE
V3 API and issues fields

### ISSUE THREAD

**Issue by b2p-fred** [lesstif/php-jira-rest-client#458]
With the V3 API set as True, an exception is raised:
```
JSON property "description" in class "JiraRestApi\Issue\IssueFieldV3" is an object and cannot be converted to a string
```
for a simple jql request on project issues:
```
        try {
            // Search new issues
            $jql = 'project = EPR and status in (New)';
            $issueService = new IssueService();
            $searchResult = $issueService->search($jql);
            foreach ($searchResult->getIssues() as $issue) {
//                var_dump($issue);
            }
        } catch (JiraException $e) {
            echo 'Error JiraException Occured! '.$e->getMessage();
        } catch (\JsonMapper_Exception $e) {
            echo 'Error JsonMapper_Exception Occured! '.$e->getMessage();
        }
```

**Comment by lesstif** [comment]
Hi @b2p-fred Thank you for your reports.

I changed the code on this [commit](https://github.com/lesstif/php-jira-rest-client/commit/525761db73ba9b832438a3b8016beb78f83cef51).
Could you check changes work well, please?

**Comment by b2p-fred** [comment]
I tried with your commit but the problem is still present. Sorry but I do not have many time at the moment to investigate.

**Comment by lesstif** [comment]
I'm so sorry. I totally misunderstood your report, and it is a bug.
Unfortunately, I do have not enough time at this time, I will fix it later.

**Comment by b2p-fred** [comment]
No matter. I do not have any emergency with this feature

**Comment by lesstif** [comment]
Hi @b2p-fred.
I was forked V3 specific repository. you can find [here](https://github.com/lesstif/php-JiraCloud-RESTAPI).

Thank you!

**Comment by GM-Alex** [comment]
@lesstif But why?
