### ISSUE TITLE
Bug fix regression #390

### ISSUE THREAD

**Issue by b2p-fred** [lesstif/php-jira-rest-client#459]
The fix reported in #390 which was fixed thanks to this PR https://github.com/lesstif/php-jira-rest-client/pull/391 is no more in the current source code !

I installed version 4.0.4 and I still have the problem reported in #390

**Comment by b2p-fred** [comment]
Indeed the #391 Prwas simply closed without merging. Any valid reason for this ?

**Comment by lesstif** [comment]
Hi @b2p-fred.

PR #391 needs to polish code and drop the unused comments, so I closed it without merged.
If you think that #391 will resolve your problem, I welcome your PR with polished code.

Thank you!

**Comment by b2p-fred** [comment]
My PR #461
