### ISSUE TITLE
Uncaught Error: Class 'IssueService' not found in jira.php

### ISSUE THREAD

**Issue by jiteshsojitra** [lesstif/php-jira-rest-client#46]
Tried php-jira-rest-client utility and its great, but i'm facing one issue.

I have installed composer and every settings in jira folder internal to sub directory and tried to run basic login but it throws "IssueService throws class not found" error. It looks like it can't find IssueService, can you please help me for this issue?

<?php
	require_once('/web/wp-content/themes/2016theme/jira/vendor/autoload.php');
	use JiraRestApi\Configuration\ArrayConfiguration;

	$iss = new IssueService(new ArrayConfiguration(
          array(
               'jiraHost' => 'https://your-jira.host.com',
               'jiraUser' => 'jira-username',
               'jiraPassword' => 'jira-password',
          )
   ));
?>

require_once('/web/wp-content/themes/2016theme/jira/vendor/autoload.php');
	use JiraRestApi\Configuration\ArrayConfiguration;

Works fine but IssueService throws class not found 

Error:

Fatal error: Uncaught Error: Class 'IssueService' not found in /web/wp-content/themes/2016theme/jira.php:13
Stack trace:	#0 /web/wp-includes/template-loader.php(75): include()
			#1 /web/wp-blog-header.php(19): require_once('/web/wp-...') 
			#2 /web/index.php(17): require('/web/wp-...') 
			#3 {main} thrown in /web/wp-content/themes/2016theme/jira.php on line 13

**Comment by lesstif** [comment]
did you put the *use JiraRestApi\Issue\IssueService;* statement in the first line?

**Comment by jiteshsojitra** [comment]
Thanks lesstif, it is solved; may be you can update this in readme as per example given of IssueService?

I already renamed .env.example to .env with valid jira user accounts as per readme but still getting below. Looks like i'm still missing something, what could be?

Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at ../.env. in /web/jira/vendor/vlucas/phpdotenv/src/Loader.php:75 Stack trace: 
	#0 /web/jira/vendor/vlucas/phpdotenv/src/Loader.php(52): Dotenv\Loader->ensureFileIsReadable() 
	#1 /web/jira/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load() #2 /web/jira/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData() 
	#3 /web/jira/vendor/lesstif/php-jira-rest-client/src/Configuration/DotEnvConfiguration.php(16): Dotenv\Dotenv->load() 
	#4 /web/jira/vendor/lesstif/php-jira-rest-client/src/JiraClient.php(70): JiraRestApi\Configuration\DotEnvConfiguration->__construct('../') 
	#5 /web/jira.php(20): JiraRestApi\JiraClient->__construct()

**Comment by jiteshsojitra** [comment]
Thanks lesstif again!

**Comment by lesstif** [comment]
have a nice day.!
