### ISSUE TITLE
Support to update Custom Fields Options?

### ISSUE THREAD

**Issue by LordSimal** [lesstif/php-jira-rest-client#465]
I know this Library states, that V3 is not yet fully supported but it would be awesome if we could support this endpoint:
https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-options/#api-rest-api-3-field-fieldid-context-contextid-option-put

Especially since self-hosted (old) JIRA instances are only supported till [february 2024](https://www.atlassian.com/migration/assess/journey-to-cloud) it would be nice if we could start migrating to the latest API

**Comment by lesstif** [comment]
Hi @LordSimal. thank you for the great suggestion.

The on-premise Jira is still alive after Feb 2024, only the Server version will be EOF in Feb 2024. :)

But v2 and v3 mixed repos operate is very difficult for me, so I fork ed v3 specific repos from this.

you can find [here](https://github.com/lesstif/php-JiraCloud-RESTAPI).

I always welcome your PR. :)

**Comment by LordSimal** [comment]
I was already preparing a PR for this but having an extra repo for the v3 is even better 😄 
Will check that out whenever I finally get admin rights to our Jira Cloud Server so I can test the updating custom fields endpoint
