### ISSUE TITLE
Epic Link

### ISSUE THREAD

**Issue by jonorherrington** [lesstif/php-jira-rest-client#47]
When using the search method of the IssueService object, the epic link for issues is not getting pulled into the fields object that it returns. Is there a way with this OO wrapper to get the epic links for issues or that feature not built in yet?

Thanks in advance.

**Comment by lesstif** [comment]
This is probably caused by no explicit JSON mapping for Epic link field.
i can't found Epic link json schema from JIRA API DOC(https://docs.atlassian.com/jira/REST/cloud/).
did you attached server returned json data?

**Comment by jonorherrington** [comment]
Sorry that was my bad. It was a custom field. I got it sorted.
