### ISSUE TITLE
Sending Issue Type But Still Getting Error

### ISSUE THREAD

**Issue by yusufalper** [lesstif/php-jira-rest-client#475]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/17886290/190633436-9eb33665-2da8-45ff-92e4-d33d044e81ed.png">

Hi. I am creating an issue and setting issue type with

->setIssueTypeAsString()

but it gives "Specify an issue type" error. And even (you can see in the photo) there is "issuetype" in the request?

What causes this problem?

**Comment by lesstif** [comment]
HI @yusufalper. Could you share a sample code with me?

**Comment by yusufalper** [comment]
@lesstif of course, I found the problem but i cannot figure out why.

`
        $issueField->setProjectKey($project_key)
            ->setSummary('summary')
            ->setIssueTypeAsString("Task")
            ->setDescription('description');
`

this works. but the following code not works;

`
        $stringVariable = 'Some String';
        $issueField->setProjectKey($project_key)
            ->setSummary('summary')
            ->setIssueTypeAsString($stringVariable)
            ->setDescription('description');
`

when i give i string variable instead of directly string into "setIssueTypeAsString", it not works.

**Comment by lesstif** [comment]
I got the "Issue type is required" error when I passed an invalid issue Type String.
check your issue type name "Some String" is correct.
