### ISSUE TITLE
JiraRestApi\ServiceDesk\Organisation\OrganisationService wrong uri

### ISSUE THREAD

**Issue by adsza** [lesstif/php-jira-rest-client#476]
Hello,

The $uri in JiraRestApi\ServiceDesk\Organisation is wrong, because "servicedeskapi" segment is duplicating in the url.

Now: https://adsza.atlassian.net/rest/servicedeskapi/servicedeskapi/organization

Good: https://adsza.atlassian.net/rest/servicedeskapi/organization

**Comment by mannes-paqt** [comment]
Duplication of 'servicedeskapi` in uri seems to be structural to all servicedesk api calls (i.e. also adding comment to request https://xxx.atlassian.net/rest/servicedeskapi/servicedeskapi/request/12345/comment) (package version v4.1.0)
