### ISSUE TITLE
JSON serialization return type warning under PHP 8.1

### ISSUE THREAD

**Issue by joachim-n** [lesstif/php-jira-rest-client#484]
Getting this warning on PHP 8.1:

> Return type of JiraRestApi\Project\Project::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/lesstif/php-jira-rest-client/src/Project/Project.php on line 118PHP message: PHP Deprecated:  Return type of JiraRestApi\Issue\IssueType::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by lesstif** [comment]
Hi @joachim-n 

Could you give me more detailed info, please?
For example, could you show me the example code?

**Comment by lesstif** [comment]
This issue has not been updated for a long time.
