### ISSUE TITLE
Updating Custom Fields?

### ISSUE THREAD

**Issue by chrdunne** [lesstif/php-jira-rest-client#49]
Hi 

Is it possible to update custom fields with you library?

Thanks
Chris

**Comment by lesstif** [comment]
to update custom field since version 1.9 available (a few minute ago :)

see https://github.com/lesstif/php-jira-rest-client#create-issue.

thanks.

**Comment by chrdunne** [comment]
Thanks. That's working for me now.
Much appreciated.

Chris

Chris Dunne
Ph: 353-86-8217982
http://ie.linkedin.com/in/chrdunne
