### ISSUE TITLE
`IssueField::duedate` unused

### ISSUE THREAD

**Issue by Schrank** [lesstif/php-jira-rest-client#491]
The field `duedate` is unused for `IssueField` and should therefore be removed. It might make sense to make `duedateString` public to make the info accessible outside of `jsonSerialize()`.

**Comment by lesstif** [comment]
Hi @Schrank . The duedate field need when getting the Issue detail information from projects that have a duedate field.

**Comment by Schrank** [comment]
🙈  Good to know, thanks!
