### ISSUE TITLE
PHP 8.2 support / some properties are still dynamically created

### ISSUE THREAD

**Issue by mwernaert** [lesstif/php-jira-rest-client#500]
\JiraRestApi\Issue\Version::$startDate
\JiraRestApi\Issue\Version::$userStartDate

\JiraRestApi\User\User::$accountType
\JiraRestApi\User\User::$locale

**Comment by lesstif** [comment]
hi @mwernaert I can't found $startDate, $userStartDate type in my project.
Have you added a custom filed to the project?

**Comment by mwernaert** [comment]
Hmm, weird. startDate appears to be a standard field as far as I can see (and userStartDate being a more human readable, like userReleaseDate):
- https://confluence.atlassian.com/adminjiraserver/managing-versions-938847201.html#Managingversions-releaseAddastartdate
- https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-project-versions/

According to the response documentation @ https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-project-versions/#api-rest-api-2-project-projectidorkey-versions-get-responses it shouldn't be included. It is in my case though. I'm using `\JiraRestApi\Project\ProjectService::getVersions()`

**Comment by lesstif** [comment]
Hi @mwernaert I got it. Check out v5.4.0, please!

**Comment by mwernaert** [comment]
Perfect, thanks!
