### ISSUE TITLE
undefined variable $response

### ISSUE THREAD

**Issue by Tansky91** [lesstif/php-jira-rest-client#51]
Hello,

class JiraClient, function upload:
$body = 'CURL HTTP Request Failed: Status Code : '
                     .$this->http_response.', URL:'.$url
                     ."\nError Message : ".$response; // @TODO undefined variable $response

I'm still waiting for you to solve this problem. Can i ask, when you plan to do it?

**Comment by lesstif** [comment]
i was fixed this bug at ver-1.9.1.

Running *composer update* will be fixes your problem.

thanks.

**Comment by Tansky91** [comment]
thanks a lot
