### ISSUE TITLE
Assignee not being set

### ISSUE THREAD

**Issue by johnxy84** [lesstif/php-jira-rest-client#510]
I'm using v5.40 and I've set the assignee name as their Jira name but the issues are still being created without the assignee field being set, is there a format it's supposed to be in? Email? or something else

<img width="527" alt="image" src="https://user-images.githubusercontent.com/16444619/236618798-f7f77468-f42e-4421-98b1-cd9b42214fdb.png">

**Comment by lesstif** [comment]
Hi @johnxy84, sorry for late reply.

You have to use the username as the AssigneeName, typically many companies use the email address as username.

in below screen capture, lesstif is the username.

<img width="827" alt="image" src="https://github.com/lesstif/php-jira-rest-client/assets/404534/6237bc9c-1b89-41b5-b982-2393654f7b36">

**Comment by johnxy84** [comment]
Hi @lesstif  thanks for the response, I don't know if we use the concept of username, but when I fetch an issue
<img width="176" alt="image" src="https://github.com/lesstif/php-jira-rest-client/assets/16444619/a6b6b4d3-3743-4d48-a8e1-08ec1f15db69">

These are the fields in the assignee property, there's no username field, is it then the accountID?
