### ISSUE TITLE
error "invalid request payload" when create or update project

### ISSUE THREAD

**Issue by zsuokira** [lesstif/php-jira-rest-client#514]
`try {
			$p = new Project();
			$p->setName('test-project123456')
				->setProjectTypeKey('software')
				->setDescription('Updated Example Project description')
				->setAssigneeType('UNASSIGNED')
			;
			$proj = new ProjectService();
			$pj = $proj->updateProject($p,'TP');
			var_dump($pj);
		} catch (JiraRestApi\JiraException $e) {
			print('Error Occured! ' . $e->getMessage());
		}`
 when I run this code, I get this error :"Invalid request payload. Refer to the REST API documentation and try again."

**Comment by lesstif** [comment]
Hi @zsuokira Which Jira version do you using?

**Comment by zsuokira** [comment]
> Hi @zsuokira Which Jira version do you using?

 "lesstif/php-jira-rest-client": "^5.5",
