### ISSUE TITLE
Empty customField

### ISSUE THREAD

**Issue by flack** [lesstif/php-jira-rest-client#525]
I have been using 3.1.1 until now and for a radiobutton customField I used 

```php
$issueField->addCustomField('customfield_12345', null);
```

to remove a previous selection. This has worked fine so far, but newer releases don't allow `null` any more. I've tried using `[]` and some other variants instead, but none of them work (I get jira errors then). If I remove the typehint, it seems to work. Is there some other way to accomplish this, or should I send a PR that changes the typehint to look like this?

```php
public function addCustomField(string $key, null|string|int|float|array $value): static
```

**Comment by lesstif** [comment]
Thank you @flack. I've merged right now!
