### ISSUE TITLE
The curl option curl_setopt($ch, CURLOPT_ENCODING, '') is not working (php 8.3.7)

### ISSUE THREAD

**Issue by majuca** [lesstif/php-jira-rest-client#534]
Hi,

In the **exec** function of the **JiraClient** class, the code **curl_setopt($ch, CURLOPT_ENCODING, '')** is causing the request to fail. The result of curl_exec is false, even though curl_getinfo($ch, CURLINFO_HTTP_CODE) returns 200.

If I comment out this line of code, the request succeeds.

My configurations:

php 8.3.7
lesstif/php-jira-rest-client": "5.8.0"

Any idee?

**Comment by majuca** [comment]
is seems to be a curl problem in PHP 8.3.7: https://github.com/php/php-src/issues/14184

**Comment by lesstif** [comment]
Hi @majuca sorry for the late reply. I released a fixed version- 5.9.0 right now. thank you!
