### ISSUE TITLE
Library stopped working

### ISSUE THREAD

**Issue by ldebrouwer** [lesstif/php-jira-rest-client#536]
This is a bit of an odd one, but the library has stopped working for me and my team all of a sudden.

Every single request through this library now returns a `$response` of `false`, with an empty body, and subsequently fails on the JsonMapper "hydration".

It was working perfectly fine last week.

To make things even weirder, local cURL requests in the terminal work absolutely fine.

I've also checked swapping it out for `lesstif/php-JiraCloud-RESTAPI`, and hitting the V3 API and I'm seeing the same issue there.

As I believe it may be an issue around how headers are set in the library, I was wondering if someone else is currently experiencing the same issue before I dig deeper into this. Because it feels like something might have changed on the Jira side that no longer gels with this library.

Or if there's any information that would be particularly useful in terms of steps to reproduce, I'll be happy to provide those.

**Comment by SerhiiKorniienko** [comment]
Hi @ldebrouwer, I have the same behaviour. Wasn't using this lib before - but can confirm that neither of them does not currently work.

Receiving `200 OK` with empty response.

Have you solved issue on your side somehow or switched to another API client implementation?

**Comment by ldebrouwer** [comment]
@SerhiiKorniienko Because I was only using a limited set of functionality from this library, I've swapped it out with a custom light-weight service using `symfony/http-foundation`, it was the easiest way forward for me at the time.

**Comment by SerhiiKorniienko** [comment]
@ldebrouwer gotcha! Thanks, thinking that way as well

**Comment by lesstif** [comment]
HI @ldebrouwer @SerhiiKorniienko thank you for your contribution. I guess it's related to https://github.com/php/php-src/issues/14184, so I'll release new version for work again,
