### ISSUE TITLE
exception 'InvalidArgumentException' with message 'JsonMapper::map() requires first argument to be an object, NULL given

### ISSUE THREAD

**Issue by Tansky91** [lesstif/php-jira-rest-client#57]
I had got this error here
https://github.com/lesstif/php-jira-rest-client/blob/master/src/Issue/IssueService.php#L147
Please, help me, thanks a lot

**Comment by CobbleCity** [comment]
Can you show us your code snipet?

**Comment by say1hello** [comment]
I think add check if $ret variable is an object would be enough

**Comment by Tansky91** [comment]
I agree with say1hello

**Comment by lesstif** [comment]
@Tansky91 i was released a version(https://github.com/lesstif/php-jira-rest-client/releases/tag/1.10.1) that fixes the issue.

**Comment by Tansky91** [comment]
Thank you, Лысый. It means "dear" from Russian
