### ISSUE TITLE
Missing argument 1 for JiraRestApi\Issue\Component::__construct(), called in ..\vendor\netresearch\jsonmapper\src\JsonMapper.php on line 544 and defined

### ISSUE THREAD

**Issue by andynguyenm** [lesstif/php-jira-rest-client#69]
My controller : 
use JiraRestApi\Issue\IssueService;
use JiraRestApi\JiraException;
try {
            $issueService = new IssueService();
            $issue = $issueService->search('status not in (Closed, Cancel, Reject, Resolved)');
        } catch (JiraException $e) {
            $this->assertTrue(false, 'testSearch Failed : ' . $e->getMessage());
            $issue = null;
        }
Please, help me to resolve this issue. Thanks in advande.

**Comment by lesstif** [comment]
@andynguyenm  sorry it's my mistake.
Running *composer update* will fixing it.
thanks.!
