### ISSUE TITLE
Class 'Illuminate\Support\ServiceProvider' not found in \JiraRestApi\JiraRestApiServiceProvider

### ISSUE THREAD

**Issue by siment** [lesstif/php-jira-rest-client#72]
Seems like one of your classes, `\JiraRestApi\JiraRestApiServiceProvider`, is extending an object that does not exist.

If you really want to use class `Illuminate\Support\ServiceProvider`, you need to require the package in your `composer.json`. So something like this:

```json
    "require": {
        "illuminate/support": "~5.4"
    },
```

I haven't investigated if you actually need to include Laravel related packages at all. That is up to you to decide.

**Comment by lesstif** [comment]
thanks for your comments.

Actually, this package does not have middleware, route, container binding that laravel service provider feature is not needed.

Thanks.
