### ISSUE TITLE
Parse error in constructor, line 77 in JiraClient.php

### ISSUE THREAD

**Issue by Steve048** [lesstif/php-jira-rest-client#75]
I must be doing something wrong as  I did a fresh install several times and get this error using your first example file to access Jira:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE ) or '{' or '$' in /var/www/html/myapp/vendor/lesstif/php-jira-rest-client/src/JiraClient.php  on line 77

* PHP Version 5.4.16  (no Laravel or twig)
* CentOS Linux release 7.1.1503 (Core)
* JIRA v6.4.1
I used your install instructions and made sure I have dotenv and jsonmapper in vendor directory
curl -sS https://getcomposer.org/installer | php
**php composer.phar require lesstif/php-jira-rest-client "^1.7.0"
php composer.phar install**
I have a new .env (but did not start with an .env.example), so it contains just this:
JIRA_HOST="https://agile.app.my-company.com"
JIRA_USER="login"
JIRA_PASS="password"

Then I execute (from command line or from browser) this example file
require 'vendor/autoload.php';

use JiraRestApi\Project\ProjectService;
use JiraRestApi\JiraException;

try {
    $proj = new ProjectService();

    $p = $proj->get('TEST');

    var_dump($p);
} catch (JiraException $e) {
    print("Error Occured! " . $e->getMessage());
}

Hopefully I'm making an obvious mistake or omission and would appreciate your help!

**Comment by Steve048** [comment]
I went to another server with PHP Version 5.6.21 and it seems to work fine.
Apparently it was the PHP version.  I don't think it is the PHP configuration because I get
"All settings correct for using Composer"  when downloading on PHP 5.4.16.
Perhaps the documentation needs to be updated from "PHP >= 5.4.9" to some later version.

**Comment by lesstif** [comment]
thanks for your comment.
I was using the new features introduced from php 5.5, but I was not updated the document.
