### ISSUE TITLE
Get labels for a certain IssueField?

### ISSUE THREAD

**Issue by frazboyz** [lesstif/php-jira-rest-client#77]
Is there currently a way to get labels for a custom IssueField that already exists(The IssueField is a select box).

**Comment by lesstif** [comment]
sorry, i can't understand what is label for custom field.
would you explain it or show me the example data  please?

**Comment by frazboyz** [comment]
So with a dropdown in Jira, it can be populated by what Jira calls 'labels'. It would be nice to get a possible list of labels.

**Comment by lesstif** [comment]
you can access it through IssueField's labels property.

```php
$issueService = new IssueService();
$ret = $issueService->get('TEST-123');

// print issue's labels.
var_dump($ret->fields->labels);
```

**Comment by frazboyz** [comment]
Cool! cheers.
