### ISSUE TITLE
Adding query argument 'validateQuery' in searchMethod

### ISSUE THREAD

**Issue by lo3ty** [lesstif/php-jira-rest-client#83]
Hi there,

I want to suggest an important improvement.
In IssueService in the search method, it would be really useful in some cases to add an argument "validateQuery" (type bool), with which someone can disable the query validation.
like so:

` 
public function search($jql, $startAt = 0, $maxResults = 15, $fields = [], $expand = [], $validateQuery=true)
    {
        $data = json_encode(array(
            'jql' => $jql,
            'startAt' => $startAt,
            'maxResults' => $maxResults,
            'fields' => $fields,
            'expand' => $expand,
            'validateQuery' => $validateQuery
        ));
`
This is needed when e.g. making OR queries on the issueKey field.
Would be really nice if you could implement that in the next release.

Lo3ty

**Comment by lesstif** [comment]
thanks for your suggestion.
it's implemented by v1.13.3

**Comment by lo3ty** [comment]
awesome! thank you very much
