### ISSUE TITLE
Get the custom fields of a transition or creating a issue.

### ISSUE THREAD

**Issue by frazboyz** [lesstif/php-jira-rest-client#88]
Is it possible to get a list of custom fields in a transition and/or an issue before actually executing the transition or creating the issue?

**Comment by lesstif** [comment]
you can access system wide custom fields using CustomFieldService, check this. -
- https://github.com/lesstif/php-jira-rest-client#get-all-field-list .

Single issue's custom field access via $issue->fields->customFields array.
- https://github.com/lesstif/php-jira-rest-client#get-issue-info
