### ISSUE TITLE
Multiple attachment uploading

### ISSUE THREAD

**Issue by camlesom** [lesstif/php-jira-rest-client#90]
Using the current addAttachments function the files are uploading individually and generating a lot of emails, looking at the JIRA documentation there seems to possibly be a better implementation that allows for bulk uploads. Would you be able to implement [this ](https://docs.atlassian.com/jira/REST/server/#api/2/issue/{issueIdOrKey}/attachments)API endpoint?

**Comment by lesstif** [comment]
Multiple files can be uploaded using multipart/form http header and different name for input parameter.

currently implementation used multipart http header, but don't generated multiple input parameters.

Contributions are always welcome!.

**Comment by lesstif** [comment]
Closed due to inactivity.
