### ISSUE TITLE
AllProjectsList Function does not retrieve all informations

### ISSUE THREAD

**Issue by maxleistner** [lesstif/php-jira-rest-client#93]
How can i get all informations with the AllProjectsList function? (https://github.com/lesstif/php-jira-rest-client#get-all-project-list)

I would like to retrieve the 'lead' or 'avatar' informations but they are not included. How can a extend the function to get these informations as well?

Thanks!

**Comment by lesstif** [comment]
hi!

AllProjectlist() function returned summarized information only, not detail info.
you can use to get() function instead.

```php
       $ps = new ProjectService();

        $projs = $ps->getAllProjects();

        foreach ($ps as $p) {
            // get detail info
            $proj = $ps->get($p->id);

            print($proj->lead);
        }
```

**Comment by lolas-freeform** [comment]
I seem to have this issue. I tried your solution but I am still not receiving the project description.

**Comment by lolas-freeform** [comment]
Sorry false alarm. Caught my error right after posting. Thanks for the response.
