### ISSUE TITLE
set @return types for methods

### ISSUE THREAD

**Issue by alexgivi** [lesstif/php-jira-rest-client#97]
for example, IssueService::create() returns Issue object.
it is need to avoid usage of variable type comments to let IDE identify type of returned object.
```php
/** @var Issue $issue */
$issue = $issueService->create($issueField);
return $issue->self;
```

**Comment by alexgivi** [comment]
also it would be good to add argument types.

**Comment by lesstif** [comment]
thanks for your suggestion.

I'd like to see a fixer for cleaning up PHPDoc blocks. 

can you recommended a good CS Fixer and some example for me?

**Comment by alexgivi** [comment]
there's no need to clean up or remove comments. it's need to complete them. I'm planning to make fork, improve comments, and make pull request to this repo.

**Comment by alexgivi** [comment]
@lesstif I made pull request https://github.com/lesstif/php-jira-rest-client/pull/98 . this issue fixed there

**Comment by alexgivi** [comment]
I use PhpStorm. PhpStorm and StyleCI have some differences in used code style. For example, PhpStorm prefers to put `@throw` clauses after `@return`. But maybe it may be configured. I've not studied this issue deeply. Also PhpStorm trait as warning `return;` instead of `return null;` in functions returning something, whereas StyleCI recommends use the first variant.

**Comment by lesstif** [comment]
@alexgivi thanks your contributions!.
